### ISSUE TITLE
tests failed

### ISSUE THREAD

**Issue by kovtunov** [ansible/ansible#1029]
When using live ebuild (-9999) from https://bugs.gentoo.org/show_bug.cgi?id=434104 I have such messages when enabling tests:

```
make -j8 tests 
PYTHONPATH=./lib nosetests -v -e \(TestPlayBook.py\|TestRunner.py\)
test_complex_enumeration (TestInventory.TestInventory) ... ok
test_complex_exclude (TestInventory.TestInventory) ... ok
test_complex_vars (TestInventory.TestInventory) ... ok
test_script (TestInventory.TestInventory) ... ok
test_script_all (TestInventory.TestInventory) ... ok
test_script_combined (TestInventory.TestInventory) ... ok
test_script_norse (TestInventory.TestInventory) ... ok
test_script_restrict (TestInventory.TestInventory) ... ok
test_script_vars (TestInventory.TestInventory) ... ok
test_simple (TestInventory.TestInventory) ... ok
test_simple_all (TestInventory.TestInventory) ... ok
test_simple_combined (TestInventory.TestInventory) ... ok
test_simple_norse (TestInventory.TestInventory) ... ok
test_simple_port (TestInventory.TestInventory) ... ok
test_simple_restrict (TestInventory.TestInventory) ... ok
test_simple_ungrouped (TestInventory.TestInventory) ... ok
test_simple_vars (TestInventory.TestInventory) ... ok
test_parse_kv_basic (TestUtils.TestUtils) ... ok
test_template_basic (TestUtils.TestUtils) ... ok
test_template_unicode (TestUtils.TestUtils) ... ok
test_template_varReplace_iterated (TestUtils.TestUtils) ... ok
test_template_whitespace (TestUtils.TestUtils) ... ok
test_varLookup_list (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative (TestUtils.TestUtils) ... ok
test_varReplace_almost_alternative2 (TestUtils.TestUtils) ... ok
test_varReplace_alternative (TestUtils.TestUtils) ... ok
test_varReplace_alternative_greed (TestUtils.TestUtils) ... ok
test_varReplace_caps (TestUtils.TestUtils) ... ok
test_varReplace_invalid_list (TestUtils.TestUtils) ... ok
test_varReplace_list (TestUtils.TestUtils) ... ok
test_varReplace_list_nolist (TestUtils.TestUtils) ... ok
test_varReplace_list_oob (TestUtils.TestUtils) ... ok
test_varReplace_middle (TestUtils.TestUtils) ... ok
test_varReplace_multiple (TestUtils.TestUtils) ... ok
test_varReplace_nested (TestUtils.TestUtils) ... ok
test_varReplace_nested_int (TestUtils.TestUtils) ... ok
test_varReplace_nested_list (TestUtils.TestUtils) ... ok
test_varReplace_notcomplex (TestUtils.TestUtils) ... ok
test_varReplace_simple (TestUtils.TestUtils) ... ok
test_varReplace_unicode (TestUtils.TestUtils) ... ok

----------------------------------------------------------------------
Ran 40 tests in 0.347s

OK
make -j8 pep8 
#############################################
# Running PEP8 Compliance Tests
#############################################
pep8 -r --ignore=E501,E221,W291,W391,E302,E251,E203,W293,E231,E303,E201,E225,E261,E241 lib/ bin/
lib/ansible/callbacks.py:28:61: E202 whitespace before ']'
lib/ansible/callbacks.py:84:17: E128 continuation line under-indented for visual indent
lib/ansible/callbacks.py:84:17: E125 continuation line does not distinguish itself from next logical line
lib/ansible/callbacks.py:124:15: E711 comparison to None should be 'if cond is not None:'
lib/ansible/callbacks.py:126:13: E128 continuation line under-indented for visual indent
lib/ansible/callbacks.py:163:118: E712 comparison to False should be 'if cond is not False:' or 'if cond:'
lib/ansible/callbacks.py:163:50: E202 whitespace before ']'
lib/ansible/utils.py:146:50: E202 whitespace before ']'
lib/ansible/utils.py:148:53: E202 whitespace before ']'
lib/ansible/utils.py:154:73: E202 whitespace before '}'
lib/ansible/utils.py:355:17: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:383:5: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:383:5: E125 continuation line does not distinguish itself from next logical line
lib/ansible/utils.py:388:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:391:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:393:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:394:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:396:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:398:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:400:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:402:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:403:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:407:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:410:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:411:9: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:415:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:417:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:421:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:423:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:425:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:426:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:435:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:436:13: E128 continuation line under-indented for visual indent
lib/ansible/utils.py:438:13: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:76:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:77:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:78:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:79:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:80:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:81:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:82:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:83:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:84:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:85:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:86:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:87:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:88:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:89:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:90:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:91:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:92:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:93:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:94:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:95:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:96:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:97:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:98:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:99:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:100:9: E124 closing bracket does not match visual indentation
lib/ansible/runner/__init__.py:100:9: E125 continuation line does not distinguish itself from next logical line
lib/ansible/runner/__init__.py:157:28: E202 whitespace before ']'
lib/ansible/runner/__init__.py:187:9: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:187:9: E125 continuation line does not distinguish itself from next logical line
lib/ansible/runner/__init__.py:267:61: E202 whitespace before ']'
lib/ansible/runner/__init__.py:293:35: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
lib/ansible/runner/__init__.py:297:41: E712 comparison to True should be 'if cond is True:' or 'if cond:'
lib/ansible/runner/__init__.py:299:41: E712 comparison to True should be 'if cond is True:' or 'if cond:'
lib/ansible/runner/__init__.py:326:60: E202 whitespace before ']'
lib/ansible/runner/__init__.py:534:17: E128 continuation line under-indented for visual indent
lib/ansible/runner/__init__.py:589:42: E202 whitespace before ']'
lib/ansible/runner/__init__.py:594:60: E202 whitespace before ']'
lib/ansible/runner/return_data.py:23:46: E202 whitespace before ']'
lib/ansible/runner/return_data.py:40:47: E202 whitespace before ']'
lib/ansible/runner/connection_plugins/paramiko_ssh.py:63:17: E128 continuation line under-indented for visual indent
lib/ansible/runner/connection_plugins/paramiko_ssh.py:64:17: E128 continuation line under-indented for visual indent
lib/ansible/runner/connection_plugins/paramiko_ssh.py:121:37: E128 continuation line under-indented for visual indent
lib/ansible/runner/action_plugins/async.py:48:12: E128 continuation line under-indented for visual indent
lib/ansible/runner/action_plugins/async.py:49:12: E128 continuation line under-indented for visual indent
lib/ansible/runner/action_plugins/async.py:50:12: E128 continuation line under-indented for visual indent
lib/ansible/runner/action_plugins/async.py:51:12: E128 continuation line under-indented for visual indent
lib/ansible/runner/action_plugins/async.py:52:9: E124 closing bracket does not match visual indentation
lib/ansible/runner/action_plugins/template.py:76:17: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:43:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:44:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:45:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:46:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:47:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:48:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:49:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:50:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:51:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:52:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:53:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:54:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:55:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:56:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:57:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:58:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:59:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:60:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:61:9: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:61:9: E125 continuation line does not distinguish itself from next logical line
lib/ansible/playbook/__init__.py:88:32: E202 whitespace before ']'
lib/ansible/playbook/__init__.py:197:70: E202 whitespace before '}'
lib/ansible/playbook/__init__.py:289:13: E128 continuation line under-indented for visual indent
lib/ansible/playbook/__init__.py:289:70: E202 whitespace before ']'
lib/ansible/playbook/play.py:29:8: E121 continuation line indentation is not a multiple of four
lib/ansible/playbook/play.py:38:8: E121 continuation line indentation is not a multiple of four
lib/ansible/playbook/play.py:87:47: E202 whitespace before ']'
lib/ansible/playbook/play.py:88:36: E202 whitespace before ']'
lib/ansible/playbook/play.py:230:48: E202 whitespace before ']'
lib/ansible/playbook/play.py:238:46: E202 whitespace before ']'
lib/ansible/playbook/task.py:34:10: E121 continuation line indentation is not a multiple of four
lib/ansible/playbook/task.py:51:36: E202 whitespace before ']'
lib/ansible/playbook/task.py:88:40: E202 whitespace before ']'
lib/ansible/playbook/task.py:129:50: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:38:80: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:64:45: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:67:70: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:71:32: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:101:75: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:102:71: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:110:65: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:114:82: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:115:78: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:117:86: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:118:74: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:120:86: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:125:70: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:127:75: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:188:73: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:268:76: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:282:57: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:285:52: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:298:40: E202 whitespace before ']'
lib/ansible/inventory/__init__.py:307:40: E202 whitespace before ']'
lib/ansible/inventory/expand_hosts.py:47:9: E125 continuation line does not distinguish itself from next logical line
lib/ansible/inventory/group.py:21:84: E202 whitespace before ']'
lib/ansible/inventory/host.py:23:43: E202 whitespace before ']'
lib/ansible/inventory/ini.py:88:21: E125 continuation line does not distinguish itself from next logical line
lib/ansible/inventory/script.py:31:35: E202 whitespace before ']'
make: [pep8] Error 1 (ignored)
pep8 -r --ignore=E501,E221,W291,W391,E302,E251,E203,W293,E231,E303,E201,E225,E261,E241 --filename "*" library/
library/apt:156:25: E711 comparison to None should be 'if cond is None:'
library/apt:174:48: E202 whitespace before ']'
library/apt:176:19: E127 continuation line over-indented for visual indent
library/apt:177:45: E202 whitespace before ']'
library/assemble:85:9: E128 continuation line under-indented for visual indent
library/assemble:86:9: E128 continuation line under-indented for visual indent
library/async_status:59:17: E128 continuation line under-indented for visual indent
library/async_wrapper:100:69: E202 whitespace before '}'
library/async_wrapper:109:13: E128 continuation line under-indented for visual indent
library/async_wrapper:157:92: E202 whitespace before '}'
library/authorized_key:67:37: E262 inline comment should start with '# '
library/authorized_key:87:47: E202 whitespace before ')'
library/authorized_key:124:12: E121 continuation line indentation is not a multiple of four
library/authorized_key:125:12: E121 continuation line indentation is not a multiple of four
library/authorized_key:126:12: E121 continuation line indentation is not a multiple of four
library/get_url:198:9: E128 continuation line under-indented for visual indent
library/get_url:199:9: E128 continuation line under-indented for visual indent
library/git:49:56: E711 comparison to None should be 'if cond is None:'
library/lineinfile:86:5: E301 expected 1 blank line, found 0
library/mount:150:52: E202 whitespace before ']'
library/mount:152:35: E202 whitespace before ']'
library/mysql_db:107:47: E711 comparison to None should be 'if cond is not None:'
library/mysql_user:207:47: E711 comparison to None should be 'if cond is not None:'
library/nagios:69:9: E123 closing bracket does not match indentation of opening bracket's line
library/nagios:89:9: E123 closing bracket does not match indentation of opening bracket's line
library/nagios:99:13: E123 closing bracket does not match indentation of opening bracket's line
library/nagios:100:9: E123 closing bracket does not match indentation of opening bracket's line
library/nagios:629:13: E123 closing bracket does not match indentation of opening bracket's line
library/nagios:657:13: E123 closing bracket does not match indentation of opening bracket's line
library/nagios:707:74: E502 the backslash is redundant between brackets
library/postgresql_db:103:17: E222 multiple spaces after operator
library/postgresql_db:110:15: E128 continuation line under-indented for visual indent
library/postgresql_db:110:45: E202 whitespace before ')'
library/postgresql_user:160:25: E127 continuation line over-indented for visual indent
library/postgresql_user:177:25: E127 continuation line over-indented for visual indent
library/postgresql_user:249:17: E222 multiple spaces after operator
library/postgresql_user:257:15: E128 continuation line under-indented for visual indent
library/postgresql_user:257:45: E202 whitespace before ')'
library/selinux:152:9: E128 continuation line under-indented for visual indent
library/selinux:153:9: E128 continuation line under-indented for visual indent
library/service:92:16: E711 comparison to None should be 'if cond is not None:'
library/service:101:16: E711 comparison to None should be 'if cond is None:'
library/service:108:16: E711 comparison to None should be 'if cond is None:'
library/service:125:16: E711 comparison to None should be 'if cond is None:'
library/service:206:26: E711 comparison to None should be 'if cond is None:'
library/setup:54:55: E202 whitespace before '}'
library/setup:55:74: E202 whitespace before '}'
library/setup:236:57: E202 whitespace before ']'
library/setup:428:41: E202 whitespace before '}'
library/setup:580:40: E202 whitespace before ')'
library/setup:707:13: E128 continuation line under-indented for visual indent
library/setup:724:12: E128 continuation line under-indented for visual indent
library/setup:723:8: E111 indentation is not a multiple of four
library/setup:725:8: E111 indentation is not a multiple of four
library/setup:726:8: E111 indentation is not a multiple of four
library/setup:727:8: E111 indentation is not a multiple of four
library/setup:728:12: E111 indentation is not a multiple of four
library/setup:729:8: E111 indentation is not a multiple of four
library/setup:730:12: E111 indentation is not a multiple of four
library/setup:731:8: E111 indentation is not a multiple of four
library/setup:732:12: E111 indentation is not a multiple of four
library/setup:733:16: E111 indentation is not a multiple of four
library/setup:734:20: E111 indentation is not a multiple of four
library/setup:735:20: E111 indentation is not a multiple of four
library/subversion:34:57: E711 comparison to None should be 'if cond is not None:'
library/subversion:35:48: E711 comparison to None should be 'if cond is not None:'
library/subversion:58:56: E711 comparison to None should be 'if cond is None:'
library/user:307:17: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
library/virt:32:17: E127 continuation line over-indented for visual indent
library/virt:38:4: E121 continuation line indentation is not a multiple of four
library/virt:39:4: E121 continuation line indentation is not a multiple of four
library/virt:40:4: E121 continuation line indentation is not a multiple of four
library/virt:41:4: E121 continuation line indentation is not a multiple of four
library/virt:42:4: E121 continuation line indentation is not a multiple of four
library/virt:43:4: E121 continuation line indentation is not a multiple of four
library/virt:44:4: E121 continuation line indentation is not a multiple of four
library/virt:52:33: E127 continuation line over-indented for visual indent
library/virt:286:17: E711 comparison to None should be 'if cond is None:'
library/virt:344:37: E202 whitespace before '}'
library/virt:350:37: E202 whitespace before '}'
library/wait_for:57:40: E202 whitespace before ')'
library/wait_for:72:40: E202 whitespace before ')'
library/yum:74:46: E202 whitespace before ']'
library/yum:84:61: E202 whitespace before ']'
library/yum:104:46: E202 whitespace before ']'
library/yum:111:61: E202 whitespace before ']'
library/yum:139:53: E202 whitespace before ']'
library/yum:147:65: E202 whitespace before ']'
library/yum:171:50: E202 whitespace before ']'
library/yum:181:65: E202 whitespace before ']'
library/yum:191:13: E127 continuation line over-indented for visual indent
library/yum:191:60: E202 whitespace before ']'
library/yum:228:60: E202 whitespace before ']'
library/yum:239:106: E202 whitespace before ']'
library/yum:241:103: E202 whitespace before ']'
library/yum:243:106: E202 whitespace before ']'
library/yum:245:96: E202 whitespace before ']'
library/yum:247:162: E202 whitespace before ']'
library/yum:253:13: E128 continuation line under-indented for visual indent
make: [pep8] Error 1 (ignored)
make -j8 pyflakes 
pyflakes lib/ansible/*.py bin/*
lib/ansible/constants.py:21: 'traceback' imported but unused
lib/ansible/utils.py:40: redefinition of unused 'json' from line 38
lib/ansible/utils.py:45: redefinition of unused '_md5' from line 43
bin/ansible-playbook:21: 'os' imported but unused
bin/ansible-pull:46: local variable 'usage' is assigned to but never used
make: *** [pyflakes] Error 1
```

As you can see, pyflakes tests are fatally failed.

**Comment by mpdehaan** [comment]
You can run "make pep8" to detect the ones we actually care about in pep8 land.   Apparently you are not running from the upstream Makefile.   Regardless, these are style considerations/suggestions, not tests.   The indents get fixed periodically.

The contents from "make pyflakes" should be fixed, but are non-lethal.

**Comment by mpdehaan** [comment]
Seems your "make pep8" doesn't support --ignore anymore, since I do see it in the CLI options.

Possibly an older (or newer) version?

**Comment by kovtunov** [comment]
pep8 has version 1.3.3.
"make pyflakes" are still failed with last git tree commit from devel branch(565f336)

**Comment by mpdehaan** [comment]
Hmm, weird, I bet they changed the argument for --ignore and it is not
properly yelling about invalid arguments.

I have 0.5.1dev here on CentOS 6.2

The other stuff is not really an error, I wouldn't really even call it
'failing' per se, we can fix in due time.
