### ISSUE TITLE
v2: delegate_to is no longer templated

### ISSUE THREAD

**Issue by ahamilton55** [ansible/ansible#11230]
##### Issue Type:

Bug Report
##### Ansible Version:

``` bash
ansible 2.0.0 (devel 24b7c353cc) last updated 2015/06/09 16:02:48 (GMT -700)
  lib/ansible/modules/core: (detached HEAD d6ed6113a7) last updated 2015/06/09 17:48:20 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 57813a2e74) last updated 2015/06/09 17:48:20 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/09 16:52:46 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/09 16:52:49 (GMT -700)
  configured module search path = /Users/andrew/workspace/ops/deploy/modules/
```
##### Ansible Configuration:

Nothing has changed since this was working with the v1 stuff.
##### Environment:

OS X 10.10.3
Python 2.7.6 (default, Sep  9 2014, 15:04:36)

Remote is Amazon Linux
##### Summary:

`delegate_to` on the new v2 branch no longer allows you to use variables for what host should be used as the delegate.

I need to template this because the hosts to delegate to change with the different environments I use ansible against.
##### Steps To Reproduce:

``` yaml

---
- hosts: tag_group_test
  vars:
    bastion: bastion-staging
  tasks:
    - uri: url=http://{{ inventory_hostname }}:8080/ timeout=5
      delegate_to: "{{ bastion }}"

    - uri: url=http://{{ inventory_hostname }}:8080/ timeout=5
      ignore_errors: True

    - debug: msg="{{ bastion }}"
```
##### Expected Results:

``` text
PLAY: ***************************************************************************

TASK [setup] ********************************************************************
ok: [ip-172-...]

TASK [uri url=http://{{ inventory_hostname }}:8080/ timeout=5] ******************
ok: [ip-172-...]

TASK [debug msg={{ bastion }}] **************************************************
ok: [ip-172-...] => {
    "msg": "bastion-staging",
    "changed": false
}

PLAY RECAP **********************************************************************
ip-172-... : ok=3    changed=0    unreachable=0    failed=0
```
##### Actual Results:

``` text
PLAY: ***************************************************************************

TASK [setup] ********************************************************************
ok: [ip-172-...]

TASK [uri url=http://{{ inventory_hostname }}:8080/ timeout=5] ******************
fatal: [ip-172-...]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "failed": true}

NO MORE HOSTS LEFT **************************************************************

PLAY RECAP **********************************************************************
ip-172-... : ok=1    changed=0    unreachable=0    failed=1
```

With more debugging:

``` text
1 plays in test.yml

PLAY: ***************************************************************************

TASK [setup] ********************************************************************
<ip-172-...> ESTABLISH SSH CONNECTION FOR USER: user
<ip-172-...> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=15 ip-172-... mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433981090.76-225676809272241 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1433981090.76-225676809272241 && echo $HOME/.ansible/tmp/ansible-tmp-1433981090.76-225676809272241
<ip-172-...> ESTABLISH SSH CONNECTION FOR USER: user
<ip-172-...> PUT /var/folders/nh/fqpr_0mx4bq4jw98sbyh78mc0000gn/T/tmpdRZ9yv TO /home/user/.ansible/tmp/ansible-tmp-1433981090.76-225676809272241/setup
<ip-172-...> ESTABLISH SSH CONNECTION FOR USER: user
<ip-172-...> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=15 ip-172-... LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1433981090.76-225676809272241/setup; rm -rf /home/user/.ansible/tmp/ansible-tmp-1433981090.76-225676809272241/ >/dev/null 2>&1
ok: [ip-172-...]

TASK [uri url=http://{{ inventory_hostname }}:8080/ timeout=5] ******************
<{{ bastion }}> ESTABLISH SSH CONNECTION FOR USER: user
<{{ bastion }}> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=15 {{ bastion }} mkdir -p $HOME/.ansible/tmp/ansible-tmp-1433981092.18-118849960710648 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1433981092.18-118849960710648 && echo $HOME/.ansible/tmp/ansible-tmp-1433981092.18-118849960710648
fatal: [ip-172-31-250-152.us-west-1.compute.internal]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /Users/user/.ssh/config\r\ndebug1: /Users/user/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/{{ bastion }}-user\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname {{ bastion }}: nodename nor servname provided, or not known\r\n", "failed": true}

NO MORE HOSTS LEFT **************************************************************

PLAY RECAP **********************************************************************
ip-172-31-250-152.us-west-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1
```

Notice aboe that **`<{{ bastion }}>`** is showing up for the host being used as the delegate.
##### Notes

I made a temporary fix on my end but I don't think that it is a correct long term fix for this issue. I placed a template in the easiest place that I could find the `delegate_to` variable used.

Here's the diff anyways:

``` diff
diff --git a/lib/ansible/executor/task_executor.py b/lib/ansible/executor/task_executor.py
index 8de8f70..9f213f6 100644
--- a/lib/ansible/executor/task_executor.py
+++ b/lib/ansible/executor/task_executor.py
@@ -208,7 +208,7 @@ class TaskExecutor:
         self._connection_info.update_vars(variables)

         # get the connection and the handler for this execution
-        self._connection = self._get_connection(variables)
+        self._connection = self._get_connection(variables, templar)
         self._connection.set_host_overrides(host=self._host)

         self._handler = self._get_action_handler(connection=self._connection, templar=templar)
@@ -361,7 +361,7 @@ class TaskExecutor:
         else:
             return async_result

-    def _get_connection(self, variables):
+    def _get_connection(self, variables, templar):
         '''
         Reads the connection property for the host, and returns the
         correct connection object from the list of connection plugins
@@ -374,6 +374,7 @@ class TaskExecutor:
             self._connection_info.remote_addr = self._host.ipv4_address

         if self._task.delegate_to is not None:
+            self._task.delegate_to = templar.template(self._task.delegate_to)
             self._compute_delegate(variables)

         conn_type = self._connection_info.connection
```

**Comment by azimut** [comment]
+1

**Comment by bcoca** [comment]
I cannot reproduce this in current devel, can you rebase and try again? It seems to work for me

**Comment by azimut** [comment]
I followed the steps on `http://docs.ansible.com/intro_installation.html` to clone from github and use env-setup. But I still have the same issue. I am doing something wrong?

The task looks like this:

```
- file: dest=/etc/noexists state=absent
  delegate_to: "{{ kickstart_master }}"
  tags:
    - kickstart
```

But is still failing:

```
# ansible-playbook -i hosts/   play.yml -vvvvv --tags=kickstart
Using /home/azimut/ansible/ansible.cfg as config file
2 plays in virt-rh7-ftp.yml

PLAY: ***************************************************************************

TASK [kickstart-rh : kickstart-rh : file dest=/etc/noexists state=absent] *******
<{{ kickstart_master }}> ESTABLISH SSH CONNECTION FOR USER: root
<{{ kickstart_master }}> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o IdentityFile="my_sshkey" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 {{ kickstart_master }} mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436377655.97-167561175922882 && echo $HOME/.ansible/tmp/ansible-tmp-1436377655.97-167561175922882
fatal: [TARGET_HOST_HERE>]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.6, OpenSSL 1.0.1g 7 Apr 2014\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/ansible-ssh-{{ kickstart_master }}-22-root\" does not exist\r\nssh: Could not resolve hostname {{ kickstart_master }}: Name or service not known\r\n", "failed": true}

PLAY RECAP **********************************************************************
<TARGET_HOST_HERE>     : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by bcoca** [comment]
so tested very simple play:

```
- hosts: localhost
  gather_facts: False
  vars:
    - testhosts:
        - nyx
  tasks:
   - shell: hostname
     delegate_to: "{{testhosts}}"
     register: myhost

   - debug: var=myhost
```

and this works fine, can yo print the value of kickstart_master in a debug?

```
ok: [localhost] => {
    "myhost": {
        "stdout": "nyx", 
        "changed": true, 
        "end": "2015-07-08 22:58:18.629239", 
        "warnings": [], 
        "cmd": "hostname", 
        "rc": 0, 
        "start": "2015-07-08 22:58:18.625686", 
        "stderr": "", 
        "delta": "0:00:00.003553", 
        "invocation": {
            "module_name": "command", 
            "module_args": {
                "_raw_params": "hostname", 
                "_uses_shell": true
            }
        }, 
        "stdout_lines": [
            "nyx"
        ]
    }, 
    "changed": false
}
```

**Comment by ahamilton55** [comment]
I have the bastion being setup in a group_vars file and it still doesn't work for me.

test.yml:

``` yaml
---
- hosts: remote_servers
  gather_facts: false
  vars_files:
    - group_vars/test
  tasks:
    - debug: msg="{{ my_var }}"

    - shell: echo $HOSTNAME
      delegate_to: "{{ bastion }}"
```

group_vars/test:

``` yaml
---
my_var: "Testing 123"

long_var: |
  blah blah blah
  blah blah blah

bastion: bastion-staging
```

Output:

```
% ansible-playbook -i deploy_conf/ec2.py -vvvv -e group=test test.yml                                                                ?[0] !10718
Using /Users/andrew/workspace/ops/deploy/deploy_conf/ansible.cfg as config file
1 plays in test.yml

PLAY: ***************************************************************************

TASK [debug msg=Testing 123] ****************************************************
ok: [ip-172-31-xxx-yyy.us-west-1.compute.internal] => {
    "msg": "Testing 123",
    "changed": false
}
ok: [ip-172-31-xxx-yyy.us-west-1.compute.internal] => {
    "msg": "Testing 123",
    "changed": false
}

TASK [command] ******************************************************************
<{{ bastion }}> ESTABLISH SSH CONNECTION FOR USER: andrew
<{{ bastion }}> ESTABLISH SSH CONNECTION FOR USER: andrew
<{{ bastion }}> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 {{ bastion }} mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436411543.42-4567463126045 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436411543.42-4567463126045 && echo $HOME/.ansible/tmp/ansible-tmp-1436411543.42-4567463126045
<{{ bastion }}> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 {{ bastion }} mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436411543.42-57103296728973 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436411543.42-57103296728973 && echo $HOME/.ansible/tmp/ansible-tmp-1436411543.42-57103296728973
fatal: [ip-172-31-xxx-yyy.us-west-1.compute.internal]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /Users/andrew/.ssh/config\r\ndebug1: /Users/andrew/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/{{ bastion }}-andrew\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname {{ bastion }}: nodename nor servname provided, or not known\r\n", "failed": true}
fatal: [ip-172-31-xxx-yyy.us-west-1.compute.internal]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /Users/andrew/.ssh/config\r\ndebug1: /Users/andrew/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/{{ bastion }}-andrew\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname {{ bastion }}: nodename nor servname provided, or not known\r\n", "failed": true}

PLAY RECAP **********************************************************************
ip-172-31-xxx-yyy.us-west-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1
ip-172-31-xxx-yyy.us-west-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1
```

Notice how in the output of the SSH command it's still trying to use the host "{{ bastion }}" instead of the variable value of "bastion-staging"

Version info:

```
ansible 2.0.0 (devel b5f3e84014) last updated 2015/07/08 20:04:44 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 8257053756) last updated 2015/07/08 20:04:52 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 639902ff20) last updated 2015/07/08 20:04:52 (GMT -700)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/09 16:52:46 (GMT -700)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/09 16:52:49 (GMT -700)
  configured module search path = /Users/andrew/workspace/ops/deploy/modules/
```

**Comment by bcoca** [comment]
showing myvar is not helpful, show bastion

**Comment by ahamilton55** [comment]
Okay. This is not of huge importance to me since I've fixed this on a local branch but the other person probably needs a prompt fix for this.

```
% ansible-playbook -i deploy_conf/ec2.py -vvvv -e group=test test.yml                                                                ?[0] !10730
Using /Users/andrew/workspace/ops/deploy/deploy_conf/ansible.cfg as config file
1 plays in test.yml

PLAY: ***************************************************************************

TASK [debug msg=bastion-staging] ************************************************
ok: [ip-172-31-9-206.us-west-1.compute.internal] => {
    "msg": "bastion-staging",
    "changed": false
}
ok: [ip-172-31-8-71.us-west-1.compute.internal] => {
    "msg": "bastion-staging",
    "changed": false
}

TASK [command] ******************************************************************
<{{ bastion }}> ESTABLISH SSH CONNECTION FOR USER: andrew
<{{ bastion }}> ESTABLISH SSH CONNECTION FOR USER: andrew
<{{ bastion }}> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 {{ bastion }} mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436413136.21-183593651585629 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436413136.21-183593651585629 && echo $HOME/.ansible/tmp/ansible-tmp-1436413136.21-183593651585629
<{{ bastion }}> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 {{ bastion }} mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436413136.21-131517543869009 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436413136.21-131517543869009 && echo $HOME/.ansible/tmp/ansible-tmp-1436413136.21-131517543869009
fatal: [ip-172-31-9-206.us-west-1.compute.internal]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /Users/andrew/.ssh/config\r\ndebug1: /Users/andrew/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/{{ bastion }}-andrew\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname {{ bastion }}: nodename nor servname provided, or not known\r\n", "failed": true}
fatal: [ip-172-31-8-71.us-west-1.compute.internal]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /Users/andrew/.ssh/config\r\ndebug1: /Users/andrew/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/{{ bastion }}-andrew\" does not exist\r\ndebug2: ssh_connect: needpriv 0\r\nssh: Could not resolve hostname {{ bastion }}: nodename nor servname provided, or not known\r\n", "failed": true}

PLAY RECAP **********************************************************************
ip-172-31-8-71.us-west-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1
ip-172-31-9-206.us-west-1.compute.internal : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment]
so i still cannot reproduce the error and the code does not have your changes.

**Comment by ahamilton55** [comment]
So your playbook above doesn't actually use the `delegate_to` attribute with the command module. You can see in the SSH output that it doesn't actually SSH to any host so this value is never templated. Can you run a test against a remote host and not localhost? I edited one of the variables to point at a host that I have:

test.yml

``` yaml
---
- hosts: localhost
  gather_facts: False
  vars:
    - testhosts:
        - bastion-staging
  tasks:
   - shell: hostname
     delegate_to: "{{testhosts}}"
     register: myhost

   - debug: var=myhost
```

```
% ansible-playbook -i deploy_conf/ec2.py -vvvv -e group=test test.yml                                   ?[0] !10736
Using /Users/andrew/workspace/ops/deploy/deploy_conf/ansible.cfg as config file
1 plays in test.yml

PLAY: ***************************************************************************

TASK [command] ******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: andrew
{{testhosts}} EXEC mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436415463.09-168897543954290 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1436415463.09-168897543954290 && echo $HOME/.ansible/tmp/ansible-tmp-1436415463.09-168897543954290
{{testhosts}} PUT /var/folders/nh/fqpr_0mx4bq4jw98sbyh78mc0000gn/T/tmp57ZEvd TO /Users/andrew/.ansible/tmp/ansible-tmp-1436415463.09-168897543954290/command
{{testhosts}} EXEC LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /Users/andrew/.ansible/tmp/ansible-tmp-1436415463.09-168897543954290/command; rm -rf /Users/andrew/.ansible/tmp/ansible-tmp-1436415463.09-168897543954290/ >/dev/null 2>&1
changed: [localhost] => {"changed": true, "end": "2015-07-08 21:17:43.177978", "stdout": "Andrews-MacBook-Pro.local", "cmd": "hostname", "start": "2015-07-08 21:17:43.167512", "delta": "0:00:00.010466", "stderr": "", "rc": 0, "invocation": {"module_name": "command", "module_args": {"_raw_params": "hostname", "_uses_shell": true}}, "stdout_lines": ["Andrews-MacBook-Pro.local"], "warnings": []}

TASK [debug var=myhost] *********************************************************
ok: [localhost] => {
    "myhost": {
        "stdout": "Andrews-MacBook-Pro.local",
        "changed": true,
        "end": "2015-07-08 21:17:43.177978",
        "warnings": [],
        "cmd": "hostname",
        "rc": 0,
        "start": "2015-07-08 21:17:43.167512",
        "stderr": "",
        "delta": "0:00:00.010466",
        "invocation": {
            "module_name": "command",
            "module_args": {
                "_raw_params": "hostname",
                "_uses_shell": true
            }
        },
        "stdout_lines": [
            "Andrews-MacBook-Pro.local"
        ]
    },
    "changed": false
}

PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by azimut** [comment]
On the example of @bcoca : assuming that "nyx" it's a remote host then the "delegate_to" works for him since he is using "hostname". It works for me too, but I had to switch to another machine and do a fresh install there in order to have it working. I can't explain that.

Back to the original issue, this still not working for me. This time I captured the output of the task that does the "delegate_to" and it shows that the values are being templated (or are being templated on the "debug" call). But it's failing somewhere else. Notice that I tried modifying the `control_path` and adding the host to `/etc/hosts`.

Playbook:

```
---
 - hosts: all
   user: root
   gather_facts: false
   roles:
     - kickstart-rh
```

Role roles/kickstart-rh/tasks/main.yml

```
---
- debug:
    var: "{{ kickstart_master }}"
  tags:
    - kickstart

- file: dest=/etc/noexists state=absent
  delegate_to: "{{ kickstart_master }}"
  register: myhost
  ignore_errors: yes
  tags:
    - kickstart

- debug:
    var: myhost
  tags:
    - kickstart
```

Output:

```
# ansible-playbook -i hosts/   virt-rh7-ftp.yml  --limit=virt67.domain.com  --tags=kickstart -vvvv
Using /root/svn/ansible/ansible.cfg as config file
1 plays in virt-rh7-ftp.yml

PLAY: ***************************************************************************

TASK [kickstart-rh : kickstart-rh : debug var=qemu5.domain.com] ************
ok: [virt67.domain.com] => {
    "changed": false, 
    "{{ kickstart_master }}": "qemu5.domain.com"
}

TASK [kickstart-rh : kickstart-rh : file dest=/etc/noexists state=absent] *******
<{{ kickstart_master }}> ESTABLISH SSH CONNECTION FOR USER: root
<{{ kickstart_master }}> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/tmp/%h-%r" -o IdentityFile="ambari_sshkey" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 {{ kickstart_master }} mkdir -p $HOME/.ansible/tmp/ansible-tmp-1436421593.86-258975598375212 && echo $HOME/.ansible/tmp/ansible-tmp-1436421593.86-258975598375212
fatal: [virt67.domain.com]: FAILED! => {"msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/tmp/{{ kickstart_master }}-root\" does not exist\r\nssh: Could not resolve hostname {{ kickstart_master }}: Name or service not known\r\n", "failed": true}
...ignoring

TASK [kickstart-rh : kickstart-rh : debug var=myhost] ***************************
ok: [virt67.domain.com] => {
    "myhost": {
        "msg": "ERROR! SSH encountered an unknown error. The output was:\nOpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\ndebug1: Reading configuration data /etc/ssh/ssh_config\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\ndebug1: auto-mux: Trying existing master\ndebug1: Control socket \"/tmp/qemu5.domain.com-root\" does not exist\nssh: Could not resolve hostname qemu5.domain.com: Name or service not known", 
        "failed": true
    }, 
    "changed": false
}

PLAY RECAP **********************************************************************
virt67.domain.com     : ok=3    changed=0    unreachable=0    failed=0   
```

Edit: my var "kickstart_master" is defined on hosts/group_vars/all.yml

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
