### ISSUE TITLE
ERROR! failed to transfer file to       ^/setup:

### ISSUE THREAD

**Issue by bonds** [ansible/ansible#13199]
I just installed Ansible devel branch like so:  `pip2 install git+https://github.com/ansible/ansible.git@devel --upgrade`. When I use any module besides `raw`, I get an error when it tries to PUT the file to the host. It seems the file name is messed up.

Ansible 1.9 works fine. I'm running OpenBSD 5.8-current with Python 2.7.10 and Fish Shell.

```
~ (master|✚29…) ❯❯❯ ansible -i ~/src/config/hosts -m setup pi.ggr.com -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<pi.ggr.com> ESTABLISH SSH CONNECTION FOR USER: None
<pi.ggr.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r -tt pi.ggr.com (umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1447809899.71-249179464121878`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1447809899.71-249179464121878`")
<pi.ggr.com> PUT /tmp/tmp1IkHgE TO       ^/setup
<pi.ggr.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r [pi.ggr.com]
pi.ggr.com | FAILED! => {
    "failed": true, 
    "msg": "ERROR! failed to transfer file to       ^/setup:\nsftp> put /tmp/tmp1IkHgE '      ^/setup'\n\nOpenSSH_7.1, LibreSSL 2.3.2\r\ndebug1: Reading configuration data /home/scott/.ssh/config\r\ndebug1: /home/scott/.ssh/config line 3: Skipping Host block because of negated match for pi.ggr.com\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 1967\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\ndebug2: Server supports extension \"fsync@openssh.com\" revision 1\r\ndebug3: Sent message fd 5 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/scott size 0\r\ndebug3: Looking up /tmp/tmp1IkHgE\r\ndebug3: Sent message fd 5 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/scott/      ^/setup\r\nremote open(\"/home/scott/      ^/setup\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"
}
```

**Comment by sivel** [comment]
What does you ansible.cfg look like?

**Comment by bonds** [comment]
I don't have a config file, here's the first line of the output:

~ (master|✚29…) ❯❯❯ ansible -i ~/src/config/hosts -m setup pi.ggr.com -vvvv
No config file found; using defaults

**Comment by jimi-c** [comment]
@bonds seems like your destination system doesn't like sftp. You can change to scp in your ansible.cfg to try and work around this, otherwise you may need to debug the sftp error manually as not much info is showing up in the output above.

http://docs.ansible.com/ansible/intro_configuration.html#scp-if-ssh

**Comment by jimi-c** [comment]
Correction, doesn't like sftp under 2.0.

cc @amenonsen

**Comment by sivel** [comment]
I'm thinking it might be elsewhere, but I don't have too much proof yet.  We see the following in the output:

```
PUT /tmp/tmp1IkHgE TO       ^/setup
```

That spacing and the `^` are what concern me.  It looks like we are somehow building a path that starts with 6 spaces and a `^`.

Eventually leading to SSH trying to `open` the following path:

```
/home/scott/      ^/setup
```

And then it fails.

**Comment by jimi-c** [comment]
@sivel ahh, I missed that. Guessing this has to do with some difference in fish then. I have an OpenBSD system at home I can install that on and test with. 

@bonds are you specifying `ansible_shell_type=fish` in your inventory? Not sure if that'll help in this situation, but it's worth testing. Looking at the fish shell plugin, it mainly only changes the way environment variables are specified.

**Comment by bonds** [comment]
@jimi-c  tried scp, same error:

```
~ (master|✚29…) ❯❯❯ mv .ansible.cfg.old .ansible.cfg
~ (master|✚29…) ❯❯❯ cat .ansible.cfg                Tue Nov 24 18:26:13 PST 2015
[ssh_connection]
scp_if_ssh=True
```

then

```
~/s/config (master|✚23…) ❯❯❯ ansible -i ~/src/config/hosts -m setup pi.ggr.com
pi.ggr.com | FAILED! => {
    "failed": true, 
    "msg": "ERROR! failed to transfer file to       ^/setup:\n\nscp:       ^/setup: No such file or directory\n"
}
```

tried `ansible_shell_type=fish`

```
~/s/config (master|✚23…) ❯❯❯ cat hosts 
[openbsd]
pi.ggr.com

[openbsd:vars]
ansible_shell_type=fish
```

unfortunately, it didn't help, got the same error

**Comment by bonds** [comment]
I switched my shell to Korn Shell and reran the command and I do NOT get the error, it works fine. So, something to do with Fish Shell 2.2 and Ansible 2.0.

```
~ (master|✚29…) ❯❯❯ fish --version                  Tue Nov 24 18:26:18 PST 2015
fish, version 2.2.0-414-g3b53abe
```

**Comment by mwilliammyers** [comment]
Not to beat a dead horse but I get the same issue when my default shell is fish on remote hosts but not when I configure my localhost with fish as my default shell. I also tried using configuring my remote hosts with `ansible_shell_type=fish` which didn't work.

The reason we are getting the error: 

```
"msg": "ERROR! failed to transfer file to       ^/setup:\n\nscp:       ^/setup: No such file or directory\n"
```

seems to be because ansible is trying to create the `setup` directory using non fish compatible commands during the connection via the initial ssh exec:

```
(umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1448742456.96-92512334359907`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1448742456.96-92512334359907`")
```

in fish, all the `&&`'s would have to be `; and`'s...

**Comment by bcoca** [comment]
so setup is a file, which should be transferred to `$HOME/.ansible/tmp/ansible-tmp-1448742456.96-92512334359907`, but the command seems to 'not fail' yet does not execute the 
`echo`, which gives back the actual directory to use. Since the return is 'empty' you get `/setup` instead of `$HOME/.ansible/tmp/ansible-tmp-1448742456.96-92512334359907/setup`.

This used to work for fish users in 1.x, I'm not sure what we changed to break it, but I'll look into it on Monday.

**Comment by bcoca** [comment]
so my PR above should fix it, i tested that it does not break sh/csh .. but have not installed fish anywhere, so please test.  I will get to the fish test on Monday, but if those affected can verify, even better.

**Comment by mwilliammyers** [comment]
I tested your PR, thanks for making one so quickly! 

It _almost_ works, but I think I have a solution. 

Here is the output of `ansible work -m ping -vvvv`:

```
Loaded callback minimal of type stdout, v2.0
<work> ESTABLISH SSH CONNECTION FOR USER: None
<work> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/wm/.ansible/cp/ansible-ssh-%h-%p-%r -tt work (umask 22 and mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1448784170.19-218016839074085`" and echo "`echo $HOME/.ansible/tmp/ansible-tmp-1448784170.19-218016839074085`")
<work> PUT /var/folders/87/xn7thmb15hqfrrh_g7wqpg_c0000gn/T/tmpzMEe2F TO       ^/setup
<work> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/wm/.ansible/cp/ansible-ssh-%h-%p-%r [work]
work | FAILED! => {
    "failed": true,
    "msg": "ERROR! failed to transfer file to       ^/setup:\nsftp> put /var/folders/87/xn7thmb15hqfrrh_g7wqpg_c0000gn/T/tmpzMEe2F '      ^/setup'\n\nOpenSSH_6.9p1, LibreSSL 2.1.7\r\ndebug1: Reading configuration data /Users/wm/.ssh/config\r\ndebug1: /Users/wm/.ssh/config line 13: Applying options for work\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 47628\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\ndebug2: Server supports extension \"fsync@openssh.com\" revision 1\r\ndebug3: Sent message fd 9 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/wm size 0\r\ndebug3: Looking up /var/folders/87/xn7thmb15hqfrrh_g7wqpg_c0000gn/T/tmpzMEe2F\r\ndebug3: Sent message fd 9 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/wm/      ^/setup\r\nremote open(\"/home/wm/      ^/setup\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"
```

You'll notice that it is picking up the `and` & `or` now, like here:

```
"`echo $HOME/.ansible/tmp/ansible-tmp-1448784170.19-218016839074085`" and echo "`echo $HOME/.ansible/tmp/ansible-tmp-1448784170.19-218016839074085`")
```

I think they need to be `; and` & `; or` instead. I haven't looked at the code too much (although I did comment on your PR on the relevant lines) but I don't think you should have any issues with Python substituting those in given that they would have spaces in them...

**Comment by mwilliammyers** [comment]
I went ahead and installed a patched version with `; and` & `; or` but it still did not work. 

It got farther without failing though: 

```
Loaded callback minimal of type stdout, v2.0
<work> ESTABLISH SSH CONNECTION FOR USER: None
<work> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<work> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<work> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<work> SSH: PlayContext set ssh_common_args: ()
<work> SSH: PlayContext set ssh_extra_args: ()
<work> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/Users/wm/.ansible/cp/ansible-ssh-%h-%p-%r)
<work> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/wm/.ansible/cp/ansible-ssh-%h-%p-%r -tt work (umask 22 ; and mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1448785120.76-6264480795962`" ; and echo "`echo $HOME/.ansible/tmp/ansible-tmp-1448785120.76-6264480795962`")
<work> PUT /var/folders/87/xn7thmb15hqfrrh_g7wqpg_c0000gn/T/tmpw1Vyv8 TO       ^/ping
<work> SSH: ansible.cfg set ssh_args: (-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
<work> SSH: ansible_password/ansible_ssh_pass not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
<work> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
<work> SSH: PlayContext set ssh_common_args: ()
<work> SSH: PlayContext set sftp_extra_args: ()
<work> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/Users/wm/.ansible/cp/ansible-ssh-%h-%p-%r)
<work> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/wm/.ansible/cp/ansible-ssh-%h-%p-%r [work]
work | FAILED! => {
    "failed": true,
    "msg": "ERROR! failed to transfer file to       ^/ping:\nsftp> put /var/folders/87/xn7thmb15hqfrrh_g7wqpg_c0000gn/T/tmpw1Vyv8 '      ^/ping'\n\nOpenSSH_6.9p1, LibreSSL 2.1.7\r\ndebug1: Reading configuration data /Users/wm/.ssh/config\r\ndebug1: /Users/wm/.ssh/config line 13: Applying options for work\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 49975\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\ndebug2: Server supports extension \"fsync@openssh.com\" revision 1\r\ndebug3: Sent message fd 9 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/wm size 0\r\ndebug3: Looking up /var/folders/87/xn7thmb15hqfrrh_g7wqpg_c0000gn/T/tmpw1Vyv8\r\ndebug3: Sent message fd 9 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/wm/      ^/ping\r\nremote open(\"/home/wm/      ^/ping\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"
}
```

I believe the issue is because the commands, like this:

```
mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1448785120.76-6264480795962`" 
```

are surrounded with: `" "` I believe fish does not expand the `$HOME`; at any rate the directory is not made when I explicitly execute the above command verbatim directly in my shell... 

Correct me if I am wrong but I don't think the `" "` are just part of the debug output...?

Also, to answer your rhetorical question (from your PR title) - because fish is an awesome shell! :smile: Ironically, the only thing that bugs me about it is this issue we are running into, but that is just due to my bash...

**Comment by bonds** [comment]
I tried https://github.com/bcoca/ansible/commit/90b31dde92554c6c84b5f454ae2d1fe759e27662 . I see the first `SSH: EXEC` line has Fish compatible syntax, but the PUT line still has the broken path, so same error as before.

```
~/s/config (master|✚42…) ❯❯❯ pip2 uninstall ansible && pip2 install git+https://github.com/bcoca/ansible.git@why_use_fish
```

then 

```
~/s/config (master|✚42…) ❯❯❯ 
ansible -i ~/src/config/hosts -m setup pi.ggr.com -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<pi.ggr.com> ESTABLISH SSH CONNECTION FOR USER: None
<pi.ggr.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r -tt pi.ggr.com (umask 22 ; and mkdir -p "( echo $HOME/.ansible/tmp/ansible-tmp-1448930949.87-113933217445256 )" ; and echo "( echo $HOME/.ansible/tmp/ansible-tmp-1448930949.87-113933217445256 )")
<pi.ggr.com> PUT /tmp/tmp_1Ucx1 TO       ^/setup
<pi.ggr.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r [pi.ggr.com]
pi.ggr.com | FAILED! => {
    "failed": true, 
    "msg": "ERROR! failed to transfer file to       ^/setup:\nsftp> put /tmp/tmp_1Ucx1 '      ^/setup'\n\nOpenSSH_7.1, LibreSSL 2.3.2\r\ndebug1: Reading configuration data /home/scott/.ssh/config\r\ndebug1: /home/scott/.ssh/config line 3: Skipping Host block because of negated match for pi.ggr.com\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 30041\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\ndebug2: Server supports extension \"fsync@openssh.com\" revision 1\r\ndebug3: Sent message fd 5 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/scott size 0\r\ndebug3: Looking up /tmp/tmp_1Ucx1\r\ndebug3: Sent message fd 5 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/scott/      ^/setup\r\nremote open(\"/home/scott/      ^/setup\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"
}
```

for comparison, using Ansible 1.9.4:

```
~/s/config (master|✚42…) ❯❯❯ 
ansible -i ~/src/config/hosts -m setup pi.ggr.com -vvvv
<pi.ggr.com> ESTABLISH CONNECTION FOR USER: scott
<pi.ggr.com> REMOTE_MODULE setup
<pi.ggr.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 pi.ggr.com /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1448931792.04-103795735350358 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1448931792.04-103795735350358 && echo $HOME/.ansible/tmp/ansible-tmp-1448931792.04-103795735350358'
<pi.ggr.com> PUT /tmp/tmp0LxcHm TO /home/scott/.ansible/tmp/ansible-tmp-1448931792.04-103795735350358/setup
<pi.ggr.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 pi.ggr.com /bin/sh -c 'env LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/local/bin/python2.7 /home/scott/.ansible/tmp/ansible-tmp-1448931792.04-103795735350358/setup; rm -rf /home/scott/.ansible/tmp/ansible-tmp-1448931792.04-103795735350358/ >/dev/null 2>&1'
pi.ggr.com | success >> {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [ ...

```

**Comment by mwilliammyers** [comment]
Still broken for me too. (pretty much the same output as above)

As far as I can tell it is not the back tics causing the problems but rather the `" "`. 
As in:

```
(umask 22 ; and mkdir -p "( echo $HOME/.ansible/tmp/ansible-tmp-1448947081.46-42464977949992 )" ; and echo "( echo $HOME/.ansible/tmp/ansible-tmp-1448947081.46-42464977949992 )")
```

Correct me if I am wrong, but I think python is passing the `" "` along to the shell to be `exec`'ed... Fish does not execute the `mkdir -p` command because it interprets that whole thing as a string and doesn't expand the command `( echo ....)`, e.g. when I run it with my local shell:

```
~
❯ mkdir -p "( echo $HOME/.ansible/tmp/ansible-tmp-1448947081.46-42464977949992 )"

~
❯ ls -al ~/.ansible/tmp/
total 0
drwxr-xr-x 2 wm staff  68 Nov 30 22:24 ./
drwx------ 4 wm staff 136 Nov 30 22:24 ../
```

**Comment by bcoca** [comment]
hmm, that is a problem cause the quotes are there to allow for special characters (mostly spaces) in the file name.

I'll look into fish docs to see how this should work

**Comment by bcoca** [comment]
ok, fish seems to 'correctly' handle spaces with () invocation, updated my PR to account for that, please test.

**Comment by bonds** [comment]
Still getting the same error:

```
~/s/config (master|✚42…) ❯❯❯ 
ansible -i ~/src/config/hosts -m setup pi.ggr.com -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<pi.ggr.com> ESTABLISH SSH CONNECTION FOR USER: None
<pi.ggr.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r -tt pi.ggr.com (umask 22 ; and mkdir -p ( echo $HOME/.ansible/tmp/ansible-tmp-1449082622.69-153223549426052 ) ; and echo ( echo $HOME/.ansible/tmp/ansible-tmp-1449082622.69-153223549426052 ))
<pi.ggr.com> PUT /tmp/tmpu5TP50 TO       ^/setup
<pi.ggr.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r [pi.ggr.com]
pi.ggr.com | FAILED! => {
    "failed": true, 
    "msg": "ERROR! failed to transfer file to       ^/setup:\nsftp> put /tmp/tmpu5TP50 '      ^/setup'\n\nOpenSSH_7.1, LibreSSL 2.3.2\r\ndebug1: Reading configuration data /home/scott/.ssh/config\r\ndebug1: /home/scott/.ssh/config line 3: Skipping Host block because of negated match for pi.ggr.com\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 23045\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\ndebug2: Server supports extension \"fsync@openssh.com\" revision 1\r\ndebug3: Sent message fd 5 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/scott size 0\r\ndebug3: Looking up /tmp/tmpu5TP50\r\ndebug3: Sent message fd 5 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/scott/      ^/setup\r\nremote open(\"/home/scott/      ^/setup\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"
}
```

**Comment by bonds** [comment]
I'm not seeing the new commit, maybe I'm doing something wrong or you forgot to push it?

https://github.com/ansible/ansible/pull/13351/commits

**Comment by bcoca** [comment]
i rebased and collapsed the commits, the new one removes quotes from fish subshels (), which made it work for me on an OpenBSD machine with fish as default shell.

**Comment by bonds** [comment]
Still getting the same error. I tried the pip install technique, I also tried checking out the branch, same result.

```
~/s/bcoca (why_use_fish|✔) ❯❯❯ git log | head -n 20 Thu Dec  3 09:08:49 PST 2015
commit c4bd7fcc890f804d6bf21107dd154f1102cdd853
Author: Brian Coca <brian.coca+git@gmail.com>
Date:   Sat Nov 28 20:37:17 2015 -0800

    Now and/or shell expressions depend on shell plugin

    This should fix issues with fish shell users as && and || are
    not valid syntax, fish uses actual 'and' and 'or' programs.
    Also updated to allow for fish backticks pushed quotes to subshell,
    fish seems to handle spaces w/o them
    fixes #13199

commit ba4e571029be059f80e8b4aab4da7578c6120e39
Author: Toshio Kuratomi <toshio@fedoraproject.org>
Date:   Mon Nov 30 19:04:33 2015 -0800

    Update submodule refs to go along with the StandardError change in ec2 moudles

commit 19d5759771be0b5c21cf788766c6eee09f2374c3
Author: Toshio Kuratomi <toshio@fedoraproject.org>
```

In the right place I think, let's try it:

```
~/s/bcoca (why_use_fish|✔) ❯❯❯ 
python2.7 bin/ansible -i ~/src/config/hosts -m setup pi.ggr.com -vvvv
No config file found; using defaults
Loaded callback minimal of type stdout, v2.0
<pi.ggr.com> ESTABLISH SSH CONNECTION FOR USER: None
<pi.ggr.com> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r -tt pi.ggr.com (umask 22 ; and mkdir -p ( echo $HOME/.ansible/tmp/ansible-tmp-1449162511.2-62809140234032 ) ; and echo ( echo $HOME/.ansible/tmp/ansible-tmp-1449162511.2-62809140234032 ))
<pi.ggr.com> PUT /tmp/tmpX8EQ8Y TO       ^/setup
<pi.ggr.com> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/scott/.ansible/cp/ansible-ssh-%h-%p-%r [pi.ggr.com]
pi.ggr.com | FAILED! => {
    "failed": true, 
    "msg": "ERROR! failed to transfer file to       ^/setup:\nsftp> put /tmp/tmpX8EQ8Y '      ^/setup'\n\nOpenSSH_7.1, LibreSSL 2.3.2\r\ndebug1: Reading configuration data /home/scott/.ssh/config\r\ndebug1: /home/scott/.ssh/config line 3: Skipping Host block because of negated match for pi.ggr.com\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 13682\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug2: Remote version: 3\r\ndebug2: Server supports extension \"posix-rename@openssh.com\" revision 1\r\ndebug2: Server supports extension \"statvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"fstatvfs@openssh.com\" revision 2\r\ndebug2: Server supports extension \"hardlink@openssh.com\" revision 1\r\ndebug2: Server supports extension \"fsync@openssh.com\" revision 1\r\ndebug3: Sent message fd 5 T:16 I:1\r\ndebug3: SSH_FXP_REALPATH . -> /home/scott size 0\r\ndebug3: Looking up /tmp/tmpX8EQ8Y\r\ndebug3: Sent message fd 5 T:17 I:2\r\ndebug3: Received stat reply T:101 I:2\r\ndebug1: Couldn't stat remote file: No such file or directory\r\ndebug3: Sent message SSH2_FXP_OPEN I:3 P:/home/scott/      ^/setup\r\nremote open(\"/home/scott/      ^/setup\"): No such file or directory\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n"
}
```

git diff shows:

```
~/s/bcoca (why_use_fish|✔) ❯❯❯ 
git diff ba4e571029be059f80e8b4aab4da7578c6120e39..c4bd7fcc890f804d6bf21107dd154f1102cdd853 | head -n 100
diff --git a/lib/ansible/plugins/shell/fish.py b/lib/ansible/plugins/shell/fish.py
index ff78941..eb8128f 100644
--- a/lib/ansible/plugins/shell/fish.py
+++ b/lib/ansible/plugins/shell/fish.py
@@ -21,5 +21,10 @@ from ansible.plugins.shell.sh import ShellModule as ShModule

 class ShellModule(ShModule):

+    _SHELL_AND = '; and'
+    _SHELL_OR = '; or'
+    _SHELL_SUB_LEFT = '('
+    _SHELL_SUB_RIGHT = ')'
+
     def env_prefix(self, **kwargs):
         return 'env %s' % super(ShellModule, self).env_prefix(**kwargs)
diff --git a/lib/ansible/plugins/shell/sh.py b/lib/ansible/plugins/shell/sh.py
index 54d2b57..94bbcbe 100644
--- a/lib/ansible/plugins/shell/sh.py
+++ b/lib/ansible/plugins/shell/sh.py
@@ -33,6 +33,10 @@ class ShellModule(object):
     # How to end lines in a python script one-liner
     _SHELL_EMBEDDED_PY_EOL = '\n'
     _SHELL_REDIRECT_ALLNULL = '> /dev/null 2>&1'
+    _SHELL_AND = '&&'
+    _SHELL_OR = '||'
+    _SHELL_SUB_LEFT = '"`'
+    _SHELL_SUB_RIGHT = '`"'

     def env_prefix(self, **kwargs):
         '''Build command prefix with environment variables.'''
@@ -67,14 +71,14 @@ class ShellModule(object):
         basetmp = self.join_path(C.DEFAULT_REMOTE_TMP, basefile)
         if system and (basetmp.startswith('$HOME') or basetmp.startswith('~/')):
             basetmp = self.join_path('/tmp', basefile)
-        cmd = 'mkdir -p "`echo %s`"' % basetmp
-        cmd += ' && echo "`echo %s`"' % basetmp
+        cmd = 'mkdir -p %s echo %s %s' % (self._SHELL_SUB_LEFT, basetmp, self._SHELL_SUB_RIGHT)
+        cmd += ' %s echo %s echo %s %s' % (self._SHELL_AND, self._SHELL_SUB_LEFT, basetmp, self._SHELL_SUB_RIGHT)

         # change the umask in a subshell to achieve the desired mode
         # also for directories created with `mkdir -p`
         if mode:
             tmp_umask = 0o777 & ~mode
-            cmd = '(umask %o && %s)' % (tmp_umask, cmd)
+            cmd = '(umask %o %s %s)' % (tmp_umask, self._SHELL_AND, cmd)

         return cmd

@@ -124,14 +128,14 @@ class ShellModule(object):
         # used by a variety of shells on the remote host to invoke a python
         # "one-liner".
         shell_escaped_path = pipes.quote(path)
-        test = "rc=flag; [ -r %(p)s ] || rc=2; [ -f %(p)s ] || rc=1; [ -d %(p)s ] && rc=3; %(i)s -V 2>/dev/null || rc=4; [ x\"$rc\" != \"xflag\" ] && echo \"${rc}  \"%(p)s && exit 0" % dict(p=shell_escaped_path, i=python_interp)
+        test = "rc=flag; [ -r %(p)s ] %(shell_or)s rc=2; [ -f %(p)s ] %(shell_or)s rc=1; [ -d %(p)s ] %(shell_and)s rc=3; %(i)s -V 2>/dev/null %(shell_or)s rc=4; [ x\"$rc\" != \"xflag\" ] %(shell_and)s echo \"${rc}  \"%(p)s %(shell_and)s exit 0" % dict(p=shell_escaped_path, i=python_interp, shell_and=self._SHELL_AND, shell_or=self._SHELL_OR)
         csums = [
             "({0} -c 'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1();{2}afile = open(\"'{1}'\", \"rb\"){2}buf = afile.read(BLOCKSIZE){2}while len(buf) > 0:{2}\thasher.update(buf){2}\tbuf = afile.read(BLOCKSIZE){2}afile.close(){2}print(hasher.hexdigest())' 2>/dev/null)".format(python_interp, shell_escaped_path, self._SHELL_EMBEDDED_PY_EOL),      # Python > 2.4 (including python3)
             "({0} -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha();{2}afile = open(\"'{1}'\", \"rb\"){2}buf = afile.read(BLOCKSIZE){2}while len(buf) > 0:{2}\thasher.update(buf){2}\tbuf = afile.read(BLOCKSIZE){2}afile.close(){2}print(hasher.hexdigest())' 2>/dev/null)".format(python_interp, shell_escaped_path, self._SHELL_EMBEDDED_PY_EOL),      # Python == 2.4
         ]

-        cmd = " || ".join(csums)
-        cmd = "%s; %s || (echo \'0  \'%s)" % (test, cmd, shell_escaped_path)
+        cmd = (" %s " % self._SHELL_OR).join(csums)
+        cmd = "%s; %s %s (echo \'0  \'%s)" % (test, cmd, self._SHELL_OR, shell_escaped_path)
         return cmd

     def build_module_command(self, env_string, shebang, cmd, arg_path=None, rm_tmp=None):
```

**Comment by bcoca** [comment]
soo ... my test setup is invalid as i cannot reproduce ...

**Comment by bonds** [comment]
I installed Fish and bcoca/ansible/why_use_fish on a fresh install of OpenBSD 5.8-release and ran the same command I've been testing with...and it worked fine! So...something seems  amiss on my day-to-day computer, perhaps there's something in my Fish config causing issues. I'll try to track it down and report back.

**Comment by bcoca** [comment]
figured out the sisue (not /bin/fish, but /usr/local/bin/fish) to reproduce the problem. I can 'fix' it for fish but it breaks for other shells. the fix removes the outside 'subshell' parens in line 81.

**Comment by bcoca** [comment]
ok, updated my PR, and works with fish on freebsd now, hopefully this will fix it for all

**Comment by bonds** [comment]
LGTM, works on my day-to-day computer now.
