### ISSUE TITLE
winrm issue: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by davidobrien1985** [ansible/ansible#13936]
Having the following problem since updating to 2.0.
I had a working CD pipeline that used Ansible. All I did was updating to 2.0 and changing my _ssh_ vars to the new names.
Now I get the following error:

```
vagrant@vagrant:/vagrant/ansible$ ANSIBLE_DEBUG=1 ansible dev -i inventory/dev -m setup -c winrm --ask-pass -vvvv
 15398 1452984398.64932: starting run
Using /vagrant/ansible/ansible.cfg as config file
SSH password:
Loaded callback minimal of type stdout, v2.0
 15398 1452984403.36082: in VariableManager get_vars()
 15398 1452984403.36372: done with get_vars()
 15398 1452984403.43481: getting the remaining hosts for this loop
 15398 1452984403.44394: done getting the remaining hosts for this loop
 15398 1452984403.44543: building list of next tasks for hosts
 15398 1452984403.44593: getting the next task for host 192.168.50.5
 15398 1452984403.44672: done getting next task for host 192.168.50.5
 15398 1452984403.45200:  ^ task is: TASK: meta
 15398 1452984403.45319:  ^ state is: HOST STATE: block=0, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
 15398 1452984403.45446: done building task lists
 15398 1452984403.45517: counting tasks in each state of execution
 15398 1452984403.45641: done counting tasks in each state of execution
 15398 1452984403.45696: advancing hosts in ITERATING_TASKS
 15398 1452984403.46150: starting to advance hosts
 15398 1452984403.46232: getting the next task for host 192.168.50.5
 15398 1452984403.46681: done getting next task for host 192.168.50.5
 15398 1452984403.47622:  ^ task is: TASK: meta
 15398 1452984403.47688:  ^ state is: HOST STATE: block=0, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
 15398 1452984403.47821: done advancing hosts to next task
 15398 1452984403.53454: done queuing things up, now waiting for results queue to drain
 15398 1452984403.55551: waiting for pending results...
 15398 1452984403.56485: no more pending results, returning what we have
 15398 1452984403.57504: results queue empty
 15398 1452984403.57961: getting the remaining hosts for this loop
 15398 1452984403.58967: done getting the remaining hosts for this loop
 15398 1452984403.59172: building list of next tasks for hosts
 15398 1452984403.59214: getting the next task for host 192.168.50.5
 15398 1452984403.59335: done getting next task for host 192.168.50.5
 15398 1452984403.59742:  ^ task is: TASK: setup
 15398 1452984403.61234:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
 15398 1452984403.61937: done building task lists
 15398 1452984403.64313: counting tasks in each state of execution
 15398 1452984403.64573: done counting tasks in each state of execution
 15398 1452984403.64716: advancing hosts in ITERATING_TASKS
 15398 1452984403.65023: starting to advance hosts
 15398 1452984403.65084: getting the next task for host 192.168.50.5
 15398 1452984403.65157: done getting next task for host 192.168.50.5
 15398 1452984403.66429:  ^ task is: TASK: setup
 15398 1452984403.66621:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=1, fail_state=0, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
 15398 1452984403.66690: done advancing hosts to next task
 15398 1452984403.67292: getting variables
 15398 1452984403.67814: in VariableManager get_vars()
 15398 1452984403.69294: done with get_vars()
 15398 1452984403.69392: done getting variables
 15398 1452984403.69624: sending task start callback, copying the task so we can template it temporarily
 15398 1452984403.69779: done copying, going to template now
 15398 1452984403.69855: done templating
 15398 1452984403.69912: here goes the callback...
 15398 1452984403.69970: sending task start callback
 15398 1452984403.70308: entering _queue_task() for 192.168.50.5/TASK: setup
 15398 1452984403.70366: 192.168.50.5 - putting task (TASK: setup) in queue
 15398 1452984403.70865: worker is 1 (out of 1 available)
 15398 1452984403.71145: exiting _queue_task() for 192.168.50.5/TASK: setup
 15398 1452984403.71283: done queuing things up, now waiting for results queue to drain
 15398 1452984403.71332: waiting for pending results...
 15408 1452984403.72334: running TaskExecutor() for 192.168.50.5/TASK: setup
 15408 1452984403.72596: in run()
 15408 1452984403.72834: calling self._execute()
 15408 1452984403.85135: WORKER PROCESS EXITING
 15407 1452984403.85457: worker 0 has data to read
 15407 1452984403.85658: got a result from worker 0: <ansible.executor.task_result.TaskResult object at 0x7f56d08dd7d0>
 15407 1452984403.85736: sending result: [u'host_task_failed', u'<ansible.executor.task_result.TaskResult object at 0x7f56d08dd7d0>']
 15407 1452984403.86111: done sending result
 15398 1452984403.86380: got result from result worker: [u'host_task_failed', u'<ansible.executor.task_result.TaskResult object at 0x7f56d08e6890>']
 15398 1452984403.86444: marking 192.168.50.5 as failed
 15398 1452984403.86526: getting the next task for host 192.168.50.5
 15398 1452984403.86592: done getting next task for host 192.168.50.5
 15398 1452984403.86740:  ^ task is: None
 15398 1452984403.86999:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=4, fail_state=2, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/process/worker.py", line 114, in run
    self._shared_loader_obj,
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 119, in run
    res = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 367, in _execute
    self._connection.set_host_overrides(host=self._host)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/winrm.py", line 97, in set_host_overrides
    if '@' in self._winrm_user:
TypeError: argument of type 'NoneType' is not iterable

192.168.50.5 | FAILED! => {
    "failed": true,
    "stdout": ""
}
 15398 1452984403.87843: no more pending results, returning what we have
 15398 1452984403.87882: results queue empty
 15398 1452984403.88020: getting the remaining hosts for this loop
 15398 1452984403.88102: done getting the remaining hosts for this loop
 15398 1452984403.88208: building list of next tasks for hosts
 15398 1452984403.88359: getting the next task for host 192.168.50.5
 15398 1452984403.88446: done getting next task for host 192.168.50.5
 15398 1452984403.88585:  ^ task is: None
 15398 1452984403.88666:  ^ state is: HOST STATE: block=1, task=1, rescue=0, always=0, role=None, run_state=4, fail_state=2, pending_setup=False, tasks child state? None, rescue child state? None, always child state? None
 15398 1452984403.88720: done building task lists
 15398 1452984403.88778: counting tasks in each state of execution
 15398 1452984403.88935: done counting tasks in each state of execution
 15398 1452984403.89017: all hosts are done, so returning None's for all hosts
 15398 1452984403.89087: done queuing things up, now waiting for results queue to drain
 15398 1452984403.89215: waiting for pending results...
 15398 1452984403.89265: no more pending results, returning what we have
 15398 1452984403.89389: results queue empty
 15398 1452984403.89447: running handlers
 15398 1452984403.89646: RUNNING CLEANUP
```

This only happens with winrm and only when using group_vars or inventory.

This works:

```
ansible dev  -i inventory/dev -m setup -c winrm -u vagrant -k -vvv
```

So it seems as if something changed and ansible is unable to get the user to connect to the target.

See also here: https://t.co/ZF7fIWCOU9

**Comment by davidobrien1985** [comment]
Is this being looked at?
Sorry, I'm really not a python guy, so I'm unable to do much more troubleshooting.

Further info about my setup maybe. This is a screenshot of my folder structure which should explain how what is being called with above ansible call.

![2016-01-18_20-06-38](https://cloud.githubusercontent.com/assets/8554521/12387231/3247588c-be1f-11e5-8ff6-7a3431c5a22a.png)

Pretty sure `remote_user` doesn't do anything, but that didn't change anything. Neither made it work nor brake further.

**Comment by jhawkesworth** [comment]
Hi,

Not sure what is happening there.  I'm still using the old names (just
haven't got round to changing) and haven't noticed a problem yet.  Can you
give that a try and report back?

Jon

**Comment by jhawkesworth** [comment]
Actually...  dug in a little to the code.

Just before the code starts looking for @ in your username, it combines
vars from the host with group vars.

Just wondering if you have any connection variables set against your
hostname as well as for your group name?

**Comment by davidobrien1985** [comment]
My folder structure from above still applies. Here's the content of my files:

`/dev/windows.yml`

```
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant
remote_port: 5986
ansible_connection: winrm
```

`/inventory/dev`

```
[dev:children]
windows

[windows]
192.168.50.5
```

`/playbooks/group_vars/dev/dev.yml`

```
---
```

This used to work. The secret file is just for demo purposes and only has a random string in it.

**Comment by jhawkesworth** [comment]
I think there's some difference in the way group_vars are resolved in
ansible 2.0

I need to test further as I'm not sure I have fully up to date ansible.cfg,
and I have some other tweaks which might be affecting things, but I noticed
today that my group vars are resolved if I run from the top level of where
my ansible configuration is held, but not if I run the playbook from a
different folder.

Could you try running the following and report back?

1/ running your ansible command from:

/vagrant/ansible/playbooks folder

2/ (temporarily) moving your /group_vars up a level so it is in
/vagrant/ansible/group_vars; then trying your ansible command again

3/ (temporarily) try moving your group_vars folder into
/vagrant/ansible/dev/group_vars; then trying your ansible command again

I think resolving group_vars is likely to be part of the issue and possibly
why only occurrs when using winrm (as connection parameters are defined in
windows group).

Many thanks,

Jon

**Comment by davidobrien1985** [comment]
Thanks Jon, unfortunately none of these worked. They all spat out the same error.
@jimi-c told me on Twitter that nothing changed around group_vars gathering, which makes me wonder why I'm seeing these issues now at the worst timing... I'm about to present on Ansible at a quite big conference in Oslo in 2 weeks. :(

**Comment by jhawkesworth** [comment]
hmm.  Not good indeed.

My impression is its something to do with where ansible winds up looking
for group_vars.  I'm sure what jimi-c says is correct, but the code
reorganisation means some things are happening at a different time and
perhaps not soon enough to be available to the winrm connection plugin.

You can get a feel for how different just by looking at the differences in
the python api between 1.9.x and 2.x -
http://docs.ansible.com/ansible/developing_api.html

I hit this when updating a custom plugin to work with 2.0.

Let me share the way I have my ansible configuration laid out - if you can
re-organise things the same way maybe you can at least get running

All my configuration is under

/etc/ansible

inventory files live in /etc/ansible - one for each environment.

underneath /etc/ansible I have

roles/
group_vars/dev/                        <-- group var files go in each
folder for each inventory
group_vars/test/
group_vars/production

playbooks go in subfolders like this
plays/provision/
plays/update/
plays/operations/
plays/verify/

I used to run plays and ad-hoc ansible commands like this

cd /etc/ansible/plays/provision
ansible-playbook -i /etc/ansible/dev_inventory
provision_some_server_type.yml

since 2.0.0.2, if I run from /etc/ansible/plays/provision my group vars
don't seem to be available

however if I run like this:

cd /etc/ansible
ansible-playbook -i dev_inventory
plays/provision/provision_some_server_type.yml

the group vars apply.

same thing with ad-hoc:

works fine:
cd /etc/ansible
ansible windows -i dev_inventory  -m win_ping

fails due to lack of group_vars
cd /etc/ansible/plays/verify
ansible windows -i /etc/ansible/dev_inventory -m win_ping

How do I know the group vars are missing?  Well that's because my custom
plugin needs group vars to do stuff and I had some print statements in it
to show the group vars.
I will see if I can cut down my plugin to demonstrate the problem, but
maybe organizing things like the above might get you unstuck for now.

Jon

**Comment by jhawkesworth** [comment]
Here's the rather messy cut-down plugin - hopefully it will demonstrate the problem a bit:

``` python
# This plugin for ansible shows group vars and host vars

from ansible import errors

from ansible.plugins.callback import CallbackBase

class CallbackModule(CallbackBase):
    """
    This plugin for ansible 2.x shows group vars and host vars
    and is intended for debugging only.
    To use, edit ansible.cfg
    1/ add it to callback_whitelist like this
    callback_whitelist = demo_group_vars
    2/ optionally set
    bin_ansible_callbacks = True
    so you can use with 'ansible' as well as 'ansible-playbook'
    3/ copy this file to somewhere on your system and set the location in ansible.cfg, e.g:
    callback_plugins = /usr/share/ansible/plugins/callback

    """
    CALLBACK_VERSION = 2.0
    CALLBACK_TYPE= 'aggregate'
    CALLBACK_ANME = 'demo_group_vars'
    CALLBACK_NEEDS_WHITELIST = True

    def __init__(self):

       super(CallbackModule, self).__init__()

       print "demo_group_vars: plugin activated"

    def __del__(self):

       print "demo_group_vars: plugin deactivated"


# the callbacks we use (on_setup and on_stats) are defined below:

    def v2_playbook_on_play_start(self, *args, **kwargs):
        print "demo_group_vars: in v2_playbook_on_play_start"
#        playbook_obj = args[0]
#        dir_pb_obj = dir(playbook_obj)
#        print "---"
#        print "---"
#        print dir_pb_obj
#        ds = playbook_obj.get_ds()
#        print "---"
#        print ds
#        handlers = playbook_obj.get_handlers()
#        print "---"
#        print handlers
#        loader = playbook_obj.get_loader()
#        print "---"
#        print loader
#        pbname = playbook_obj.get_name()
#        print "---"
#        print pbname
#        var_mgr = playbook_obj.get_variable_manager()
#        print "---"
#        print var_mgr
#        dir_var_mgr = dir(var_mgr)
#        print "var mgr methods:"
#        print dir_var_mgr
#        print "try to get inventory from var_mgr"
#        inventory = var_mgr._inventory
#        print "---"
#        print inventory
#        print type(inventory)
#        dir_inventory = dir(inventory)
#        print "inventory methods"
#        print dir_inventory
#        print "try to get hosts from inventory"
#        hosts = inventory.get_hosts()
#        print hosts
#        print type(hosts)
#        dir_hosts = dir(hosts)
#        print "hosts methods"
#        print dir_hosts
#        print "try to get vars from hosts"
#        vars = playbook_obj.get_vars()
#        print "---"
#        print vars
#        print "---"
#        for k, v in vars.iteritems():
#            print "key value: ---"
#            print k, v
        hosts = args[0].get_variable_manager()._inventory.get_hosts()
        for host in hosts:
            print "demo_group_vars: Considering host: %s" % (host)
            #print "in list of hosts"
            #print type(host)
            #print host
            #dir_host = dir(host)
            #print dir_host
            host_variables = host.get_vars()
            #print "host variables type:"
            #print type(host_variables)
            #print "host_variables methods:"
            #dir_host_variables = dir(host_variables)
            #print dir_host_variables
            print "=== kv of host_variables"
            for vk, vv in host_variables.iteritems():
                print vk, vv

            host_grp_vars = host.get_group_vars()
            print "==== group vars ==="
            #print type(host_grp_vars)
            print "==== host group var key vals:"
            for hgk, hgv in host_grp_vars.iteritems():
                print hgk, hgv

        print "demo_group_vars: finished showing host and group vars"

#end of plugin
```

**Comment by davidobrien1985** [comment]
Hi,
sorry, took a while to test this further. I'm about to jump on a plane tomorrow to Europe and my Ansible demos are still not working.
I tried what you suggested (moving group_vars) and tried calling the playbook from different places, nothing worked.
I am still getting the same error.

Would be great to get some official feedback as to where group_vars are now supposed to go.

By the way, even tried removing the whole group_vars folder and I'm still getting the same error message. :(

**Comment by jhawkesworth** [comment]
Were you able to try the plugin?  I still think the issue is that your group_vars aren't getting loaded.

Looking at ansible/playbook/play_context.py remote_user is set either from 'ansible_ssh_user' 'ansible_user'.  It's clearly None by the time it reaches the winrm connection plugin 

Probably clutching at straws here but just wondering if it is worth trying with a fresh ansible.cfg?
I found a lot of diffs when I moved from 1.9.4 to 2.0.0.2 so in the end I just worked out what differences I needed and then set them in the ansible.cfg that came with 2.0.0.2

Could you try running with a -vvvvv instead of with ANSIBLE_DEBUG - it might give some insight into where the remote user is going missing.

**Comment by davidobrien1985** [comment]
Sorry, no, wasn't able to test the plugin, but it looks like it's working again. My deployments are green again.

I did two things, right now I have no idea what in the end fixed it.

I moved `/dev/windows.yml` from above into `playbooks/group_vars/dev/windows.yml` .
I also reset my `ansible.cfg` back to default.

This fixed it. As I said, my previous setup worked perfectly fine on 1.9.4 and broke as soon as I updated to 2.0.0.2.

**Comment by jhawkesworth** [comment]
Very glad to hear you are working again.

It seems odd that you had to move your group vars folder though.

If you could diff your old ansible.cfg and the working one I'd be happy to have a look and see if there's something in the old one which might have affected finding the group_vars dir?

**Comment by davidobrien1985** [comment]
That's easy. My old `ansible.cfg` was empty, the new one is here:

```
# config file for ansible -- http://ansible.com/
# ==============================================

# nearly all parameters can be overridden in ansible-playbook
# or with command line flags. ansible will read ANSIBLE_CONFIG,
# ansible.cfg in the current working directory, .ansible.cfg in
# the home directory or /etc/ansible/ansible.cfg, whichever it
# finds first

[defaults]

# some basic default values...

#inventory      = /etc/ansible/hosts
#library        = /usr/share/my_modules/
#remote_tmp     = $HOME/.ansible/tmp
#forks          = 5
#poll_interval  = 15
#sudo_user      = root
#ask_sudo_pass = True
#ask_pass      = True
transport      = smart
#remote_port    = 22
#module_lang    = C

# plays will gather facts by default, which contain information about
# the remote system.
#
# smart - gather by default, but don't regather if already gathered
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default, must say gather_facts: True
#gathering = implicit

# additional paths to search for roles in, colon separated
#roles_path    = /etc/ansible/roles

# uncomment this to disable SSH key host checking
#host_key_checking = False

# change the default callback
#stdout_callback = skippy
# enable additional callbacks
#callback_whitelist = timer, mail

# change this for alternative sudo implementations
#sudo_exe = sudo

# What flags to pass to sudo
# WARNING: leaving out the defaults might create unexpected behaviours
#sudo_flags = -H -S -n

# SSH timeout
#timeout = 10

# default user to use for playbooks if user is not specified
# (/usr/bin/ansible will use current user as default)
remote_user = vagrant

# logging is off by default unless this path is defined
# if so defined, consider logrotate
#log_path = /var/log/ansible.log

# default module name for /usr/bin/ansible
#module_name = command

# use this shell for commands executed under sudo
# you may need to change this to bin/bash in rare instances
# if sudo is constrained
#executable = /bin/sh

# if inventory variables overlap, does the higher precedence one win
# or are hash values merged together?  The default is 'replace' but
# this can also be set to 'merge'.
#hash_behaviour = replace

# by default, variables from roles will be visible in the global variable
# scope. To prevent this, the following option can be enabled, and only
# tasks and handlers within the role will see the variables there
#private_role_vars = yes

# list any Jinja2 extensions to enable here:
#jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n

# if set, always use this private key file for authentication, same as
# if passing --private-key to ansible or ansible-playbook
#private_key_file = /path/to/file

# format of string {{ ansible_managed }} available within Jinja2
# templates indicates to users editing templates files will be replaced.
# replacing {file}, {host} and {uid} and strftime codes with proper values.
#ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
# This short version is better used in templates as it won't flag the file as changed every run.
#ansible_managed = Ansible managed: {file} on {host}

# by default, ansible-playbook will display "Skipping [host]" if it determines a task
# should not be run on a host.  Set this to "False" if you don't want to see these "Skipping"
# messages. NOTE: the task header will still be shown regardless of whether or not the
# task is skipped.
#display_skipped_hosts = True

# by default (as of 1.3), Ansible will raise errors when attempting to dereference
# Jinja2 variables that are not set in templates or action lines. Uncomment this line
# to revert the behavior to pre-1.3.
#error_on_undefined_vars = False

# by default (as of 1.6), Ansible may display warnings based on the configuration of the
# system running ansible itself. This may include warnings about 3rd party packages or
# other conditions that should be resolved if possible.
# to disable these warnings, set the following value to False:
#system_warnings = True

# by default (as of 1.4), Ansible may display deprecation warnings for language
# features that should no longer be used and will be removed in future versions.
# to disable these warnings, set the following value to False:
#deprecation_warnings = True

# (as of 1.8), Ansible can optionally warn when usage of the shell and
# command module appear to be simplified by using a default Ansible module
# instead.  These warnings can be silenced by adjusting the following
# setting or adding warn=yes or warn=no to the end of the command line
# parameter string.  This will for example suggest using the git module
# instead of shelling out to the git command.
# command_warnings = False


# set plugin path directories here, separate with colons
#action_plugins     = /usr/share/ansible/plugins/action
#callback_plugins   = /usr/share/ansible/plugins/callback
#connection_plugins = /usr/share/ansible/plugins/connection
#lookup_plugins     = /usr/share/ansible/plugins/lookup
#vars_plugins       = /usr/share/ansible/plugins/vars
#filter_plugins     = /usr/share/ansible/plugins/filter
#test_plugins       = /usr/share/ansible/plugins/test

# by default callbacks are not loaded for /bin/ansible, enable this if you
# want, for example, a notification or logging callback to also apply to
# /bin/ansible runs
#bin_ansible_callbacks = False


# don't like cows?  that's unfortunate.
# set to 1 if you don't want cowsay support or export ANSIBLE_NOCOWS=1
#nocows = 1

# set which cowsay stencil you'd like to use by default. When set to 'random',
# a random stencil will be selected for each task. The selection will be filtered
# against the `cow_whitelist` option below.
#cow_selection = default
#cow_selection = random

# when using the 'random' option for cowsay, stencils will be restricted to this list.
# it should be formatted as a comma-separated list with no spaces between names.
# NOTE: line continuations here are for formatting purposes only, as the INI parser
#       in python does not support them.
#cow_whitelist=bud-frogs,bunny,cheese,daemon,default,dragon,elephant-in-snake,elephant,eyes,\
#              hellokitty,kitty,luke-koala,meow,milk,moofasa,moose,ren,sheep,small,stegosaurus,\
#              stimpy,supermilker,three-eyes,turkey,turtle,tux,udder,vader-koala,vader,www

# don't like colors either?
# set to 1 if you don't want colors, or export ANSIBLE_NOCOLOR=1
#nocolor = 1

# if set to a persistent type (not 'memory', for example 'redis') fact values
# from previous runs in Ansible will be stored.  This may be useful when
# wanting to use, for example, IP information from one group of servers
# without having to talk to them in the same playbook run to get their
# current IP information.
#fact_caching = memory


# retry files
# When a playbook fails by default a .retry file will be created in ~/
# You can disable this feature by setting retry_files_enabled to False
# and you can change the location of the files by setting retry_files_save_path

#retry_files_enabled = False
#retry_files_save_path = ~/.ansible-retry


# prevents logging of task data, off by default
#no_log = False

# prevents logging of tasks, but only on the targets, data is still logged on the master/controller
#no_target_syslog = False

# controls the compression level of variables sent to
# worker processes. At the default of 0, no compression
# is used. This value must be an integer from 0 to 9.
#var_compression_level = 9

[privilege_escalation]
#become=True
#become_method=sudo
#become_user=root
#become_ask_pass=False

[paramiko_connection]

# uncomment this line to cause the paramiko connection plugin to not record new host
# keys encountered.  Increases performance on new host additions.  Setting works independently of the
# host key checking setting above.
#record_host_keys=False

# by default, Ansible requests a pseudo-terminal for commands executed under sudo. Uncomment this
# line to disable this behaviour.
#pty=False

[ssh_connection]

# ssh arguments to use
# Leaving off ControlPersist will result in poor performance, so use
# paramiko on older platforms rather than removing it
#ssh_args = -o ControlMaster=auto -o ControlPersist=60s

# The path to use for the ControlPath sockets. This defaults to
# "%(directory)s/ansible-ssh-%%h-%%p-%%r", however on some systems with
# very long hostnames or very long path names (caused by long user names or
# deeply nested home directories) this can exceed the character limit on
# file socket names (108 characters for most platforms). In that case, you
# may wish to shorten the string below.
#
# Example:
# control_path = %(directory)s/%%h-%%r
#control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r

# Enabling pipelining reduces the number of SSH operations required to
# execute a module on the remote server. This can result in a significant
# performance improvement when enabled, however when using "sudo:" you must
# first disable 'requiretty' in /etc/sudoers
#
# By default, this option is disabled to preserve compatibility with
# sudoers configurations that have requiretty (the default on many distros).
#
#pipelining = False

# if True, make ansible use scp if the connection type is ssh
# (default is sftp)
#scp_if_ssh = True

# if False, sftp will not use batch mode to transfer files. This may cause some
# types of file transfer failures impossible to catch however, and should
# only be disabled if your sftp version has problems with batch mode
#sftp_batch_mode = False

[accelerate]
#accelerate_port = 5099
#accelerate_timeout = 30
#accelerate_connect_timeout = 5.0

# The daemon timeout is measured in minutes. This time is measured
# from the last activity to the accelerate daemon.
#accelerate_daemon_timeout = 30

# If set to yes, accelerate_multi_key will allow multiple
# private keys to be uploaded to it, though each user must
# have access to the system via SSH to add a new key. The default
# is "no".
#accelerate_multi_key = yes

[selinux]
# file systems that require special treatment when dealing with security context
# the default behaviour that copies the existing context or uses the user default
# needs to be changed to use the file system dependent context.
#special_context_filesystems=nfs,vboxsf,fuse,ramps
```

**Comment by jhawkesworth** [comment]
Well not a lot of difference there then if you take out the commented out and blank lines

cat dobrien-ansible.cfg | grep -v "^#" | grep -v "^$"
[defaults]
transport      = smart
remote_user = vagrant
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]

**Comment by jhawkesworth** [comment]
I'm afraid I'm out of ideas.  Since you are up and running and you have things organised as per the documentation, do you want to pursue this further?

**Comment by jimi-c** [comment]
Hi @davidobrien1985. In 2.0, we've moved variable names around a little, though I'm surprised this isn't working. Connection variables are now of the form `ansible_*` or `ansible_<connection>_*`. So in your case, I believe either setting `ansible_user` or `ansible_winrm_user` will get you around this problem.

**Comment by jimi-c** [comment]
Additionally, I believe we should catch the situation in the winrm connection plugin when the username is not set, as I don't think that's ever valid for a Windows connection. cc @nitzmahone

**Comment by nitzmahone** [comment]
Only case I could see where we'd want to pick up an ambient username (ala ssh behavior) would be kerberos SSO (ie, logged into control via krb, want to log into Windows with same interactive user). Behavior change regardless- anyone else want to weigh in on "pick up ambient user like SSH" or "bomb if user is not specified"?

**Comment by jhawkesworth** [comment]
I agree kerberos is the only case I can think of where you might want to pick up ambient username (and pre-existing kerberos ticket).  Its not actually how I run things myself but wouldn't want to shut the door to it.

**Comment by ghost** [comment]
Just a heads up on this one. We've got it as well after upgrading to 2.0. I'm expecting to be able to use the ambient username from a kerberos ticket as our build server will be running this particular task so it allows us to isolate the credentials from the build script.

**Comment by nitzmahone** [comment]
I have a fix for this that I'll be committing for 2.1, and likely backporting to at least 2.0.x (in case we do another 2.0.x release). It's a little sticky, as pykerberos' support for explicit principals is currently broken, and pywinrm has usually been just ignoring the principal, but I hope to fix pykerberos' support so we can use it to support collection ccaches (eg, for seamless user switching, multi-user playbooks). If we pass a principal that doesn't match kerb's default principal, it would fail, where it used to succeed (but use the default principal instead of finding a ticket for the user you asked for).

**Comment by ghost** [comment]
Thanks - much appreciated. Let me know if there's a branch I can pull to test if this does get backported. If not I'll hang back 'til 2.1.

**Comment by nitzmahone** [comment]
This is in current 2.1RC1 and devel. There aren't currently plans for a 2.0.3- I might backport if we do, but otherwise, grab 2.1. Closing...
