### ISSUE TITLE
async failing when using become_user

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13965]
I'm running ansible as root and the task that I want to run async has a `become_user: deploy`. I'm trying to "fire-and-forget" using a poll interval of zero.

I'm getting an error: `fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The async task did not return valid JSON: No JSON object could be decoded"}`.

I see that ansible created an `~/.ansible_async` folder in the deploy users home directory. Looking at the output of the json in there it looks like the task runs successfully.

I'm assuming that the polling mechanism isn't looking in the correct directory. I.e. its looking in `/root/.ansible_async` instead of `/home/deploy/.ansible_async`.

Hopefully the provided code will help you reproduce:

```
# /root/ansible/test.yml
- name: async test
  hosts: localhost
  become: yes
  become_user: root
  roles:
    - async_test
```

```
# /root/ansible/roles/async_test/tasks/main.yml

---
- name: (async) run echo
  become: yes
  become_user: deploy
  command: echo 'foobar'
  async: 300 # 5mins
  poll: 0
  register: echo_register

- name: (sync) Check that echo ran correctly
  async_status: jid={{ echo_register.ansible_job_id }}
  register: job_result
  until: job_result.finished
  delay: 10
  retries: 30
```

Running as root:

```
# ansible-playbook -i localhost, test.yml --connection=local -vvvv
Using /root/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in test.yml

PLAY [async test] **************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: root
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453140819.25-48014692489709 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453140819.25-48014692489709 )" )
localhost PUT /tmp/tmp1maULN TO /root/.ansible/tmp/ansible-tmp-1453140819.25-48014692489709/setup
localhost EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453140819.25-48014692489709/setup; rm -rf "/root/.ansible/tmp/ansible-tmp-1453140819.25-48014692489709/" > /dev/null 2>&1
ok: [localhost]

TASK [async_test : (async) Install the bundle] *********************************
task path: /root/ansible/roles/async_test/tasks/main.yml:2
ESTABLISH LOCAL CONNECTION FOR USER: root
localhost EXEC ( umask 22 && mkdir -p "$( echo /tmp/ansible-tmp-1453140819.4-51686115790218 )" && echo "$( echo /tmp/ansible-tmp-1453140819.4-51686115790218 )" )
localhost PUT /tmp/tmpjdh1ME TO /tmp/ansible-tmp-1453140819.4-51686115790218/command
localhost EXEC chmod a+rx /tmp/ansible-tmp-1453140819.4-51686115790218/command
localhost PUT /tmp/tmpuID4hD TO /tmp/ansible-tmp-1453140819.4-51686115790218/async_wrapper
localhost EXEC chmod a+rx /tmp/ansible-tmp-1453140819.4-51686115790218/async_wrapper
localhost PUT /tmp/tmpjDGsih TO /tmp/ansible-tmp-1453140819.4-51686115790218/arguments
localhost EXEC /bin/sh -c 'sudo -H -S -n -u deploy /bin/sh -c '"'"'echo BECOME-SUCCESS-qtdbiptxugcspdlfjygaqdxrqojfzbqm; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /tmp/ansible-tmp-1453140819.4-51686115790218/async_wrapper 81376111153 300 /tmp/ansible-tmp-1453140819.4-51686115790218/command /tmp/ansible-tmp-1453140819.4-51686115790218/arguments'"'"''
localhost EXEC rm -f -r /tmp/ansible-tmp-1453140819.4-51686115790218/ > /dev/null 2>&1
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The async task did not return valid JSON: No JSON object could be decoded"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

```
# cat ~deploy/.ansible_async/81376111153.3881
{"changed": true, "end": "2016-01-18 18:13:39.489280", "stdout": "foobar", "cmd": ["echo", "foobar"], "rc": 0, "start": "2016-01-18 18:13:39.487886", "stderr": "", "delta": "0:00:00.001394", "invocation": {"module_args": {"warn": true, "executable": null, "chdir": null, "_raw_params": "echo 'foobar'", "removes": null, "creates": null, "_uses_shell": false}}, "warnings": []}
```

If I comment out `become_user: deploy` the task passes.

I'm using ansible 2.0.0.2 which is latest as of this report.

**Comment by ghost** [comment]
I believe the issue is something similar to https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/raw.py#L45-L46. It seems that the output of the command has `BECOME-SUCCESS-fkkoodgbkhbyceewgrhrumordptazfkx` as part of stdout which is not being striped.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by jimi-c** [comment]
One thing I did notice about your play example was, in the task where you're checking the async task, you need to use the same `become` settings, otherwise the task fails because the log file async_status checks for is in the wrong user's directory.

**Comment by ghost** [comment]
Thanks @jimi-c, appreciate the quick merge!

**Comment by viviliv** [comment]
It looks like this is still a problem. 

ansible --version
ansible 2.1.0.0

 FAILED! => {"changed": false, "failed": true, "msg": "The async task did not return valid JSON: No JSON object could be decoded"

**Comment by ssbarnea** [comment]
This is true. We have the same bug in Ansible 2.1.0.0! Nobody is reading the issue tracker? We cannot reopen bugs.

**Comment by jimi-c** [comment]
@viviliv / @ssbarnea have you tested with the 2.1.1 rc's or devel?

**Comment by jimi-c** [comment]
There are several other reasons this bug may be hit, and some fixes were put into devel/stable-2.1 in the last month to address them.

**Comment by ssbarnea** [comment]
First problem that I see that `pip2 install --pre ansible` does not find the prerelease version of ansible. I guess you missed to published them to https://testpypi.python.org :(

**Comment by abadger** [comment]
You should also open a new issue.  Since this was fixed in January, it's
likely similar assumptions but a new bug.  Additionally, we don't always
see new comments on closed bugs so a new bug is a much better way to get
attention for a problem.

**Comment by jimi-c** [comment]
@ssbarnea we don't push the RC's to pypi yet, it's something we're planning on doing but haven't gotten some time to implement.
