### ISSUE TITLE
Hipchat Callback not working

### ISSUE THREAD

**Issue by ThoTischner** [ansible/ansible#16946]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /root/ansible/ansible.cfg
  configured module search path = ['modules']
```
##### CONFIGURATION

```
[defaults]
library = modules
log_path = /tmp/ansible.log
roles_path = roles
callback_plugins = callbacks/
deprecation_warnings=False
callback_whitelist = hipchat
```
##### OS / ENVIRONMENT

CentOS7
##### SUMMARY

Hipchat Callback: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/hipchat.py 
is not working. 
Vars can not be set.
##### STEPS TO REPRODUCE

Enable hipchat callback via ansible.cfg whitelisting.
Configure the required Hipchat ENV-Vars.
Run any playbook, following error occurs:

```
PLAY [Staging Packages] ********************************************************
 [WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin (</usr/lib/python2.7/site-packages/ansible/plugins/callback/hipchat.CallbackModule object at 0x31c4750>):
'Play' object has no attribute 'playbook'
 [WARNING]: Failure using method (v2_playbook_on_stats) in callback plugin (</usr/lib/python2.7/site-packages/ansible/plugins/callback/hipchat.CallbackModule object at 0x2c4c750>):
'CallbackModule' object has no attribute 'display'
```
##### EXPECTED RESULTS

Message send to hipchat room.
##### ACTUAL RESULTS

Hipchat message not working
##### MISC

The display error can be solved by changing the callback from:
self.display.warning('
to
self._display.warning('

**Comment by alikins** [comment]
Looks like the 'self.play' error has been fixed in devel/ already, and https://github.com/ansible/ansible/pull/16998 is a pr to fix the 'self.display' issue.

**Comment by ThoTischner** [comment]
Hi,

thanks for your fast reply.

I cloned the actual master and tried to run it via:
/usr/local/src/ansible/bin/ansible-playbook -i inventory/qsu2/ playbooks/staging.yml -M /usr/local/src/ansible/lib/ansible/modules/ -vvv

hipchat.py files was patched => display warning is not a problem anymore.

## But following error still appears:

PLAY [Staging Packages] ********************************************************
 [WARNING]: Failure using method (v2_playbook_on_play_start) in callback plugin (</root/ansible/callbacks/hipchat_org.CallbackModule object at 0x20e25d0>): 'Play' object has no attribute

## 'playbook'

Are the old ansible libs still getting used or why this error persists?
