### ISSUE TITLE
Anisble does not allow handling of "host unreachable" errors

### ISSUE THREAD

**Issue by dpedu2** [ansible/ansible#18287]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Anible core (?)

##### ANSIBLE VERSION
```
ansible 2.1.0.0
  config file = /home/ubuntu/my/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/my/anisble/library/']
```

I updated to 2.2.0.0 and the behavior is identical.

##### CONFIGURATION
```
[defaults]
forks = 100
nocows = 1

[ssh_connection]
ssh_args = -o ConnectTimeout=20 -o ConnectionAttempts=2 -o ForwardAgent=yes -o ServerAliveInterval=10 -o ServerAliveCountMax=300 -o StrictHostKeyChecking=no -F /home/ubuntu/my/ansible/ssh.config
```

ssh.config contains:
```
Host *
ServerAliveInterval 10
ServerAliveCountMax 300
TCPKeepAlive yes
StrictHostKeyChecking no
ControlMaster auto
ControlPath ~/.ssh/mux-%r_%h:%p
ControlPersist 1h
ForwardAgent yes
User ubuntu
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible does not allow handling of "host unreachable" errors. The following methods of handling errors do not catch "host unreachable" errors and do not allow playbook logic to detect and act upon such situations:

##### STEPS TO REPRODUCE

 - Use any technique mentioned in ansible's [Error Handling](http://docs.ansible.com/ansible/playbooks_error_handling.html) doc
- Hit a temporary 'host unreachable' error on the play
- The error is not caught or error-handling logic is not triggered.

Attempts to catch the error:

Retries:

```
    - name: Example step
      shell: whoami
      retries: 10
      register: task_result
      until: task_result|success
```

Try/catch block:

```
  - block:
    - name: Example step
      shell: whoami
    rescue:
    - local_action: shell echo do nothing
```

##### EXPECTED RESULTS
Host Unreachable errors are handled by the error-handling logic in the playbook

##### ACTUAL RESULTS
Ansible behaves as if the error-handling logic does not exist.

**Comment by bcoca** [comment]
Those are for errors on the execution of the task, communication errors (unreachable) can be cleared using the a`meta`  task. http://docs.ansible.com/ansible/meta_module.html

**Comment by dpedu2** [comment]
Thanks for the info - that workaround will probably work in my case. Though I still think allowing programming of custom handling would be useful.

**Comment by dpedu2** [comment]
After testing, it seems `- meta: clear_host_errors` (and `refresh_inventory`) does not clear unreachable host errors.

**Comment by berney** [comment]
> After testing, it seems - meta: clear_host_errors (and refresh_inventory) does not clear unreachable host errors.

This might be related meta: clear_host_errors not working on tasks #19673.

**Comment by bcoca** [comment]
closing this as fixed via #19958

**Comment by Rudd-O** [comment]
I applied the above PR manually to my Ansible install, and it certainly does not make `clear_host_errors` work.

**Comment by Rudd-O** [comment]
This code in `linear.py`

```py
    def run(self, iterator, play_context):
        '''
        The linear strategy is simple - get the next task and queue
        it for all hosts, then wait for the queue to drain before
        moving on to the next task
        '''

        # iteratate over each task, while there is one left to run
        result = self._tqm.RUN_OK
        work_to_do = True
        while work_to_do and not self._tqm._terminated:
            try:
                display.debug("getting the remaining hosts for this loop")
                hosts_left = [host for host in self._inventory.get_hosts(iterator._play.hosts) if host.name not in self._tqm._unreachable_hosts]
```

See how it excludes unreachable hosts from running?

I suspect this means Ansible never gets to the `meta` handler.

**Comment by Rudd-O** [comment]
Yes, that is correct.  When hosts_left is empty, then host_tasks gets nothing.

```py
    def _get_next_task_lockstep(self, hosts, iterator):
        '''
        Returns a list of (host, task) tuples, where the task may
        be a noop task to keep the iterator in lock step across
        all hosts.
        '''

        noop_task = Task()
        noop_task.action = 'meta'
        noop_task.args['_raw_params'] = 'noop'
        noop_task.set_loader(iterator._play._loader)

        host_tasks = {}
        display.debug("building list of next tasks for hosts")
        for host in hosts:
            host_tasks[host.name] = iterator.get_next_task_for_host(host, peek=True)
        display.debug("done building task lists")

        num_setups = 0
        num_tasks  = 0
        num_rescue = 0
        num_always = 0

        display.debug("counting tasks in each state of execution")
        host_tasks_to_run = [(host, state_task)
                             for host, state_task in iteritems(host_tasks)
                             if state_task and state_task[1]]

        if host_tasks_to_run:
            try:
                lowest_cur_block = min(
                    (s.cur_block for h, (s, t) in host_tasks_to_run
                    if s.run_state != PlayIterator.ITERATING_COMPLETE))
            except ValueError:
                lowest_cur_block = None
        else:
            # empty host_tasks_to_run will just run till the end of the function
            # without ever touching lowest_cur_block
            lowest_cur_block = None

        for (k, v) in host_tasks_to_run:
            (s, t) = v

            if s.cur_block > lowest_cur_block:
                # Not the current block, ignore it
                continue

            if s.run_state == PlayIterator.ITERATING_SETUP:
                num_setups += 1
            elif s.run_state == PlayIterator.ITERATING_TASKS:
                num_tasks += 1
            elif s.run_state == PlayIterator.ITERATING_RESCUE:
                num_rescue += 1
            elif s.run_state == PlayIterator.ITERATING_ALWAYS:
                num_always += 1
        display.debug("done counting tasks in each state of execution:\n\tnum_setups: %s\n\tnum_tasks: %s\n\tnum_rescue: %s\n\tnum_always: %s" % (num_setups, num_tasks, num_rescue, num_always))
```

The PR does not fix the bug.  I'm disappoint :-(

**Comment by Rudd-O** [comment]
To reproduce: run a playbook where you have a task that returns unreachable and a following `clear_failed_hosts meta` task, but only run it against a *single host*.  Running against two hosts, one of which does not raise unreachable from the first task, will **not** trigger the error.

Bam, instant reproducer.

Please reopen this issue.  Thanks.

**Comment by cazorla19** [comment]
Let's get up this issue. Please, reopen this. It's really painful when you work with autoscaling group on the cloud.
What's the issue exactly? Let's start with, for example, 20 nodes gathering info from EC2 dynamic inventory. A couple of them might be terminated by EC2 API to scale down. If they will, Ansible marks these hosts as unreachable, finish all tasks on helathy nodes. But! It returns "exit code 4" which means error.
The issue is that it sometimes doesn't seem to be error at all. But the target CI system (Jenkins, Bamboo, whatever) marks this operation as an error and breaks the full operational cycle. Meta task doesnt work on multiple nodes. Even if it will, it's going to try to connect to hosts again which seems unreasonable at this situation.
It treats by a shell-wrapper which handles "4 exit code", but, surely, this is a nasty workaround. So, please, include the meta or any other engine which helps to signal Ansible that unreachable is OK and we don't need to return error if some nodes (for example, by percentage) will be unreachable&

**Comment by Maghin** [comment]
I would like to automate a very simple task: changing ssh port after a common server install. It would have been great if the following worked:

**In Inventory:**
```
# Hosts
myserver ansible_port=1234
```

**First task in playbook:**
```
- block:
  - name: Check if ssh port is configured
    ping: ~
  rescue:
    - name: Change SSH port
      include: "change_ssh_port.yml"
      vars:
        ansible_port: 22
```

Unfortunatly adding the following to the ```ping``` task doesn't work either.
```
register: result
failed_when: result | unreachable
```

**Comment by pjnagel** [comment]
Here is another use case:

We use nexmo module to notify our developers of the progress of a very long-running deployment task. We wrapped it all in a top-level `rescue` block so we can send notification if any step failed.

However, in the case of unreachable errors, we get NO notification at all due to this issue.

For this use case, `meta: clear_failed_hosts` is also not ideal, because even if it worked, we would need to add it after each and every tasks in our playbook, or otherwise there would be no notification of unreachable failures.

For this type of use case, something like a `rescue` block that handles **all** errors, including unreachable, would be ideal.

**Comment by paxsonsa** [comment]
Does anyone else agree we need to revisit how we are handling unreachable errors? 

We have a use case where we are using a play to secure our servers. While securing our servers we disable ssh logins with root. If the setup is run again on secured node it will obvious fail because the root user is not permitted for ssh logins.

Our inventory is dynamic meaning we could have 1000 nodes all secured or 1000 nodes and 'n' unsecured. 

The problem we encounter is the secure role runs as root initially and by the end of play, root login is disabled. For the nodes that are unsecured the play runs not problem but for the nodes that are secured the get an unreachable error.  We want to be able to handle that and pass it. The method mention above does not seem to work when all nodes are secured. The play is stopped. 

I agree with the idea that `rescue` should be able to catch unreachable errors and decide what to due next. 

For now we have made sure that our infrastructure code runs the setup play when the node is initialized but I think being able to have the option to handle unreachable errors would be very helpful

**Comment by Unix-Mike** [comment]
I will not use Ansible because of the lack of error handling for unreachable hosts

**Comment by berney** [comment]
Related (open) issues:
  - #26227 clear_host_errors not working
  - #35086 clear_host_errors causes unexpected behaviour with unreachable hosts

**Comment by TylerKerrACG** [comment]
This still needs to be looked at. This breaks any sort of notification handling for an unreachable host. Ansible 2.5.4 still has this issue.

**Comment by UnitedMarsupials-zz** [comment]
Meanwhile, the work-around for people developing inventory-verification related tasks:

1. Attempt the task on each host as usual, register into a variable (such as `verification`).
2. On `localhost` loop through _all_ hosts (`groups["all"]`) looking for `"unreachable": true`

For example:
```yaml
- hosts: all
  gather_facts: false
  tasks:
  - name: Collect package-versions for each specified file
    shell: "rpm -qf {{ thefiles }}"
    args:
      warn: false
    changed_when: false
    register: pkgs
    ignore_errors: true

- hosts: localhost
  tasks:
  - meta: clear_host_errors
  - debug: var=hostvars[item].pkgs.msg
    with_items: "{{ groups['all'] }}"
    when: hostvars[item].pkgs.unreachable is defined
```
That is, the unreachable host remains unused, but you can still produce a report of connection-failures (desirable or otherwise) on whatever host you are running the playbook on.

**Comment by TylerKerrACG** [comment]
@UnitedMarsupials solution is not a complete resolution. That playbook will not solve the issue in Tower because limiting the scope in the tower UI will break running the second task on localhost unless it is also in the same scope.
Additionally, in the instance that you are using win_ping to test windows connectivity and tower is running on Linux you cannot leave localhost in the same scope or it will fail.

This needs actual error handling.

**Comment by UnitedMarsupials-zz** [comment]
@TylerKerrACG, of course, it needs actual error-handling. I was just offering a work-around. If Ansible refuses to do anything on a host, to which it failed to connect earlier, _another_ host (such as `localhost`) can do some of the reporting/error-handling.

It is partial -- and the `gather_facts` better be `false`, or it will not work, but it allowed me to do my work and may help others.

**Comment by pupseba** [comment]
It would be nice if this get fixed. Is not a new thing and the workarounds, depending on the tasks, are pretty unpractical, verbose traditional script like (verify machine is powered on and use different things for each provider, veryfiy if connection to ssh port exists, then run a command...almost easy to do with a bash script...
I would use the "powerstate" modules for some providers but as they rely on the tools installed on the vm, they can also fail if the tools are not reachable for any reason.
So much trouble just to poweroff vms is not cool :/

**Comment by bcoca** [comment]
https://github.com/ansible/ansible/pull/43857

**Comment by tomtastic** [comment]
Also just encountered this issue, adding my support to @bcoca 's PR.
