### ISSUE TITLE
git: "failed to get the hostkey for" error after update to version 2.2.1

### ISSUE THREAD

**Issue by lempa** [ansible/ansible#20653]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION
ansible 2.2.1.0
  config file = ~/.ansible.cfg
  configured module search path = Default w/o overrides

```
[defaults]
host_key_checking = False
```

##### OS / ENVIRONMENT

Ubuntu 14.04.5 LTS (remote)
macos sierra (local)

##### SUMMARY

With this version the git task stops with this message: `failed to get the hostkey for HOST`
The HOST is normally accessible via non default SSH port.

##### STEPS TO REPRODUCE

```yaml
- name: Clone the project to the new release folder
       git: repo={{git_repo}}
            dest={{ deploy_helper.new_release_path }}
            version={{git_branch}}
            accept_hostkey=yes
```

##### EXPECTED RESULTS

It should work like in previous version v2.2.0.0

##### ACTUAL RESULTS

```
fatal: [DEPLOY_USER]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "accept_hostkey": true, 
            "bare": false, 
            "clone": true, 
            "depth": null, 
            "dest": "RELEASE_PATH", 
            "executable": null, 
            "force": true, 
            "key_file": null, 
            "recursive": true, 
            "reference": null, 
            "refspec": null, 
            "remote": "origin", 
            "repo": "REPO", 
            "ssh_opts": null, 
            "track_submodules": false, 
            "umask": null, 
            "update": true, 
            "verify_commit": false, 
            "version": "develop"
        }, 
        "module_name": "git"
    }, 
    "msg": "failed to get the hostkey for HOST"
}

```

**Comment by ppinette** [comment]
+1

**Comment by eljenso** [comment]
I am having the same issue.
Just downgraded to version 2.1.2.0 and git module passed.

**Comment by eljenso** [comment]
Looks like this behavior was introduced with https://github.com/ansible/ansible/commit/0d9afa84d50e02c912e90ff6bbe5a89cea30b8be

**Comment by s-hertel** [comment]
Update:
I was able to recreate this using a different port.

needs_info
I wasn't able to recreate this on OS-X 10.12.2
```
ansible 2.2.1.0
  config file = /Users/.../ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
`host_key_checking = False`

Playbook:
```
---
- hosts: localhost
  connection: local
  tasks:
  - name: Clone the project to the new folder
    git:
      repo: "{{ repo }}"
      dest: "{{ dest }}"
      version: "{{ branch }}"
      accept_hostkey: "yes"
```
Outcome:
```
changed: [localhost] => {
    "after": "c95076789853bfef79b88f323775d0b486a04430",
    "before": null,
    "changed": true,
    "invocation": {
        "module_args": {
            "accept_hostkey": true,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "PATH",
            "executable": null,
            "force": false,
            "key_file": null,
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "REPO",
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "devel"
        },
        "module_name": "git"
    },
    "warnings": []
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```
Perhaps another bug- it asks for my passphrase twice, both in Ansible version 2.2.1.0 and 2.3.0.

**Comment by eljenso** [comment]
@s-hertel What port is your remote's SSH running on?
@lempa's as well as my remote are not running on 22.

**Comment by salamachinas** [comment]
I am having the same issue.
Running playbook on local machine.

```
Ubuntu 16.04.1 LTS
```

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "accept_hostkey": true, 
            "bare": false, 
            "clone": true, 
            "depth": 100, 
            "dest": "/home/user/destination", 
            "executable": null, 
            "force": false, 
            "key_file": null, 
            "recursive": true, 
            "reference": null, 
            "refspec": null, 
            "remote": "origin", 
            "repo": "ssh://private-repository.com/some-repository.git", 
            "ssh_opts": null, 
            "track_submodules": false, 
            "umask": null, 
            "update": true, 
            "verify_commit": false, 
            "version": "HEAD"
        }, 
        "module_name": "git"
    }, 
    "msg": "failed to get the hostkey for private-repository.com"
}
```

**Comment by eljenso** [comment]
@salamachinas What port are you using?

**Comment by selble** [comment]
Another victim of this change here. We're running our Git server on port 7999, and were setting "accept_hostkey" to "true". I found removing that parameter, and setting ssh_opts="-o StrictHostKeyChecking=no" was an acceptable workaround in our case.

**Comment by salamachinas** [comment]
@eljenso 2222

**Comment by aslheyrr** [comment]
Same issue, both local and remote, but is random occurrence.

Ubuntu 14.04 LTS

ansible 2.2.1.0

``host_key_checking = False``


    git:  
        repo: <WHATEVER>  
        dest: <WHATEVER>
        version: <WHATEVER>
        update: yes
        force: yes
        accept_hostkey: yes
        key_file: <WHATEVER>

Got:
``fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed to get the hostkey for bitbucket.org"}``

**Comment by TheSameCH** [comment]
"Same issue", but I figured out that in our case the problem is not the code of https://github.com/ansible/ansible/commit/0d9afa84d50e02c912e90ff6bbe5a89cea30b8be. Unfortunately none of you guys posted a repo URL, so I can not tell if you run into the same issue.

Issue: The `add_host_key` function presumes that one is connecting to default SSH port 22. If you have a git repo like `ssh://git@git.company.com:7999/project`, the function will fail. The port needs to get extracted from the URL and passed to the function, so `ssh-keyscan` can be run wit option `-p 7999` for example.

**Comment by stffndtz** [comment]
@eljenso replying for @lempa: We're not running on Port 22.

What seemed to fix the issue for us though was using a dedicated ansible_user and adding the key to known_hosts by running a ssh-keyscan command manually.

EDIT: and of course adding the port to the ssh config.

**Comment by selble** [comment]
@TheSameCH, thank you, and apologies for not posting the URL we are using. Ours indeed follows the problematic format you listed.

**Comment by eljenso** [comment]
@TheSameCH Our URL looks something like `ssh://git@gitlab.example.org:55/eljenso/project.git`. So your issue might be the same issue everyone here is experiencing.

**Comment by vmichnowicz** [comment]
I had the same issue with Ansible 2.2.1.0. Uninstalling Ansible and reinstalling a previous versions seems to have fixed this issue.

```
pip uninstall ansible
pip install 'ansible==2.1.2.0'
```

My Ansible git deploy looks something like this:

```
- name: deploy code
  git: repo=ssh://git@192.168.0.1:7999/project/repo.git
```

**Comment by alanjds** [comment]
Same issue here, even on standard 22 port. Standard bitbucket private project, like this: `git: repo=git@bitbucket.org:myprivateteam/myprivaterepo.git dest=/opt/projects/private accept_hostkey=yes`

**Comment by TheSameCH** [comment]
@alanjds You are using git protocol and not SSH, so this can not be the same issue. Just try to replace the `:` with a `/`: `git@bitbucket.org/myprivateteam/myprivaterepo.git`

**Comment by alanjds** [comment]
@TheSameCH You can be right, but worked after installed Anisible 2.2.0.0 and was broken with 2.2.1.0

**Comment by Toub** [comment]
Same issue (with non standard port URL), back to 2.1.2.0 as suggested by @vmichnowicz as a workaround until this issue is solved.

**Comment by emielmolenaar** [comment]
Same issue here on Debian Jessie with Ansible 2.2.1.0, trying to checkout a git repo via standard SSH port 22.

**Comment by alexphelps** [comment]
I had the same issue, host_key_checking is set to false, and git module has accept_host_key to yes. It actually only happens the first time I run the playbook, all runs after that work correctly.

**Comment by adoram** [comment]
Same issue here:
repo: ssh://our.dev.server:22000/git/sdev.git

We have downgraded to Ansible 2.2.0 and it works fine, but it's not a permanent solution...

**Comment by flaugher** [comment]
Same problem here.  Ansible 2.2.1.0, Debian 8.7, repo is git@bitbucket.org:<myname>/<mysite>.git.  Interestingly, I don't get this error if run on macOS Sierra.

**Comment by RaymiiOrg** [comment]
I had the same issue, with a git server via an SSH config. The port forward runs on port 9022, and not on 22.

    accept_hostkey: yes

didn't work, same error. The following did work:

    ssh_opts: "-o StrictHostKeyChecking=no  -o Port=9022 "

(Explicitly giving the port as ssh option)

**Comment by s-hertel** [comment]
@robinro

**Comment by robinro** [comment]
According to @eljenso this regression was introduced by @abadger in #18698. @jctanner reviewed it. Maybe @abadger or @jctanner can look into this?

**Comment by s-hertel** [comment]
Does using command line `$ git clone ssh://host:port/the/repo` work for anyone experiencing this problem?
Trying to clone my bitbucket.org repo: `ssh://git@bitbucket.org:443/my/repo` fails - in the playbook with the `failed to get the hostkey` error and with command line 
```ssh_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
If I change the repo to `ssh://git@altssh.bitbucket.org:443/my/repo` though it succeeds.

I'm not really sure how to fix the problem, but I think the bug is due to the args passed to module_utils.basic.run_command() or the ssh configuration. Run_command args is equal to `"/usr/bin/ssh-keyscan -t rsa -p 443 bitbucket.org"` for me and it returns nothing. If I set args equal to `"/usr/bin/ssh-keyscan -t rsa bitbucket.org"` it works. Running that on the command line shows what port is expected (which is 22). Is anyone else experiencing that as well? That suggests user error to me but I don't know.

**Comment by imranh2** [comment]
Hi all.

I think I know what's going on here. Does everyone here have hashed known_hosts turned on?

Because if you do then there is a bug in one of the module_utils that the git module uses. - #22445

**Comment by realflash** [comment]
What is that and how would we know?

**Comment by imranh2** [comment]
@realflash ```$ grep "HashKnownHosts" /etc/ssh/ssh_config``` will tell you, at least on a default debian install.

**Comment by walterdolce** [comment]
> $ grep "HashKnownHosts" /etc/ssh/ssh_config will tell you

There are many places where this directive could be configured, i.e. the user's `~/.ssh/config` file.

**Comment by realflash** [comment]
HashKnownHosts yes

I am affected the first time I run the play. After that the problem goes away. Not configured in user's config file. But I would add that I am using the standard SSH port, so that bug doesn't seem relevant to me.

**Comment by gijbelst** [comment]
Hi,
Same problem here and affected in every run.  
@imranh2, HashKnownHosts is turned on.

**Comment by aes512** [comment]
Workaround that we are using:

```
ssh_trusted_servers:
  - sub.domain.tld

pre_tasks:
  - set_fact: git_rsa_keys={{ lookup('pipe', 'ssh-keyscan -t rsa ' + ssh_trusted_servers | join(' ')).splitlines() }}
    until: git_rsa_keys | count >= ssh_trusted_servers | count
    retries: 10
    delay: 10
    when: git_rsa_keys is not defined

  - lineinfile:
      dest: '~{{ ansible_env.USER }}/.ssh/known_hosts'
      create: yes
      state: present
      line: "{{ item }}"
      regexp: "{{ '^' + item.split(' ').0 | regex_escape() }}"
    with_items: '{{ git_rsa_keys }}'
```

**Comment by shadycuz** [comment]
Same issue here 
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
and 
```
host_key_checking = False
```
Task looks like 
```
- name: Cloning Repo
  become: false
  become_user: xxxxx
  git:
    repo: ssh://git@gitlab.com:myrepo/xxxxxx.git
    dest: /home/user/xxxxxxx
    accept_hostkey: yes
```
Error
```
TASK [myrole : Cloning Repo] *************************************************************************************************
fatal: [server01]: FAILED! => {"changed": false, "failed": true, "msg": "failed to get the hostkey for gitlab.com"}
        to retry, use: --limit @/etc/ansible/test.retry
```

This happens even if I run it twice.

Works fine from cmd line.

The fix for me was removing the ssh:// prefix from the gitlab url.

**Comment by adoram** [comment]
@imranh2 HashKnownHosts is on, ssh uses non-standard port on the latest Amazon Linux. For now continuing to use Ansible 2.2.0.0, but will try to add the "-o Port=9022" ssh_opts option.
Any ETA for this to be fixed?
Thanks!

**Comment by robinro** [comment]
AFAIK nobody is working on this yet (@abadger @jctanner Correct me if I'm wrong)

@adoram or anyone else: Feel free to open a PR.
!needs_info
needs_contributor

**Comment by abadger** [comment]
I believe this was fixed by willthames in this PR: https://github.com/ansible/ansible/pull/20840

The commit is in the latest stable-2.2, stable-2.3, and devel branches.  I've just confirmed that  ansible-2.2.2.0.tar.gz and ansible-2.3.0.0.tar.gz contain that fix as well.

Now the fun part... from some of the comments, I'm not sure if everyone is experiencing the same bug.  If someone is still experiencing this bug with 2.2.2.0, 2.3.0, or a recent checkout please let us know with as much information as you can for us to reproduce.  (git url, HashKnownHosts setting, alternate ports, ssh confg for the git host if you can, ansible version,  etc).

If no one replies, we'll close this issue as fixed by #20840 in a few days (but if you later test and find the bug still exists, absolutely feel free to open a new bug with a reproducer.)

needs_info

**Comment by alikins** [comment]
Somewhat related: https://github.com/ansible/ansible/issues/19440 ("git module needs better error messages for timeout related errors"). #19440 seems to imply the "failed to get the hostkey for..." error message can be a bit vague, which would lend credence to @abadger thoughts about this potentially being caused by different issues.

**Comment by abadger** [comment]
From some debugging work done by @jctanner, at least for @shadycuz, the issue is that the git repo specified, ssh://git@gitlab.com:myrepo/xxxxxx.git isn't valid.  As you found, it should look more like one of these two:

* git@gitlab.com:myrepo/xxxxxx.git
* ssh://git@gitlab.com/~myrepo/xxxxxx.git

Using the ```ssh://``` prefix with ```:myrepo``` mixes the format for ssh specifying a location with the format for a location specified in a URI and fails (If you try it with git clone on the command line, git clone will fail as well).

**Comment by Buzut** [comment]
I'm really sorry you closed this issue because as of Ansible 2.3.0.0 (latest pip install on Mac OS 10.11.6), I still experience the issue.

```yaml
- name: Clone git backend
  git:
    repo: git@gogs.xxx.xxx:project/backend.git
    dest: /var/www/project
    accept_hostkey: yes
    key_file: /root/.ssh/git/id_ed25519
```

It used to work but now, if it's the first connection, it will fail if the git server's hostkey isn't in `known_hosts`.

In the meantime, I've found a workaround in my playbooks: manually adding the git server's hostkey via `echo "xxx" >> /root/.ssh/known_hosts`

**Comment by HighCaliberConsecrator** [comment]
Also getting 'failed to get hostkey for [host]' from the git module, updated to 2.3.0.0. to see if  it fixed but still seeing it, accept_hostkey: yes is set

Running from ubuntu 14.04 to  a github url,  tried disabling strict checking on the remote host (where the clone is happening) in the .ssh/config  but didn't make a difference.  HashKnownHosts is on (default on ubuntu I think)

**Comment by abadger** [comment]
If you're seeing this issue with the proper urls, please open a new issue.  There's no one monitoring closed issues so the new reports being added here aren't being seen by anyone who can help out with the problem.  A reproducer that we can run would be the best way thing that hte new issue could contain.

Thanks for your help in getting this resolved!
