### ISSUE TITLE
 AttributeError: 'Host' object has no attribute 'remove_group' in 2.2.2.0

### ISSUE THREAD

**Issue by jamielennox** [ansible/ansible#23016]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
```ansible/inventory/__init__.py", line 181```

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /home/ubuntu/hoist/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In the upgrade to 2.2.2.0 we started seeing the error: 
```
ERROR! Unexpected Exception: 'Host' object has no attribute 'remove_group'
```
It _looks_ like when https://github.com/ansible/ansible/commit/36b462ba857361ba310c7967a721c025c13d2225 was cherry-picked but not https://github.com/ansible/ansible/commit/c4cff44e772e8b4631386243169d164bc0b0937c which actually adds the remove_group to the Host object.

##### STEPS TO REPRODUCE
The inventory file we are using was a stub to do a --syntax-check and looked like: 
```
test-bastion ansible_ssh_host=127.0.0.1 ansible_ssh_user=ubuntu

[bastion]
test-bastion
```
Full command was (playbook doesn't matter): 
```
ansible-playbook -vvvvv -i tests/files/test-inventory --syntax-check restart.yml
```

##### EXPECTED RESULTS
Runs syntax check in 2.2.1.0

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ansible-playbook", line 103, in <module>
    exit_code = cli.run()
  File "/home/ubuntu/.local/venvs/ansible/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 132, in run
    inventory = Inventory(loader=loader, variable_manager=variable_manager, host_list=self.options.inventory)
  File "/home/ubuntu/.local/venvs/ansible/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 97, in __init__
    self.parse_inventory(host_list)
  File "/home/ubuntu/.local/venvs/ansible/local/lib/python2.7/site-packages/ansible/inventory/__init__.py", line 181, in parse_inventory
    host.remove_group(ungrouped)
AttributeError: 'Host' object has no attribute 'remove_group'
```

**Comment by dutt** [comment]
Hi,
I just apt-upgraded ansible and ran into this, when will the ubuntu ppa receive the fix so I can run ansible again? 
Is there a manual workaround until it's deployed?

**Comment by enandrei** [comment]
you can install the old one from the ubuntu repos  ( sudo apt install ansible=2.1.1.0-1~ubuntu16.04.1 )

**Comment by dutt** [comment]
Thanks for the help, could you show the command? I've tried various forms of that but I always get 
`"E: Version '2.1.1.0-1' for 'ansible' was not found"` so it seems I'm missing something. I've tried

`sudo apt install ansible=2.1.1.0-1ppa-xenial`
`sudo apt install ansible=2.1.1.0-1ppa`
`sudo apt install ansible=2.1.1.0-1`
`sudo apt install ansible=2.1.1.0`

**Comment by enandrei** [comment]
I edited my previous response with the full name. In case it still  doesn't work , search for available packages.

apt policy ansible
ansible:
  Installed: 2.1.1.0-1~ubuntu16.04.1
  Candidate: 2.2.2.0-1ppa~xenial
  Version table:
     2.2.2.0-1ppa~xenial 500
        500 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial/main amd64 Packages
 *** 2.1.1.0-1~ubuntu16.04.1 100
        100 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
        100 /var/lib/dpkg/status
     2.0.0.2-2ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     2.0.0.2-2 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

**Comment by dutt** [comment]
That part worked very nicely, many thanks for your help. But I ran into https://github.com/ansible/ansible/issues/17495 so it seems I have to wait until 2.2 is fixed.

**Comment by robkorv** [comment]
I did not have the old version in my package manager's cache. So I fixed it with a temporary virtualenv.
```bash
# create virtualenv
virtualenv venv
# activate it
. ./venv/bin/activate
# install ansible 2.2.1.0
pip install ansible==2.2.1.0
# do you ansible stuff here

# when you're done
# deactivate virtualenv
deactivate

# remove virtualenv
rm -Rf venv
```

**Comment by HanXHX** [comment]
I confirm this bug. Installed with pip. I downgraded to 2.2.1.0.

**Comment by asimayub** [comment]
I can confirm this bug too ansible 2.2.2.0 installed with pip too.  Downgraded to 2.2.1.0 no problems anymore.

**Comment by e-alfred** [comment]
This bug still exists in 2.2.2.0 from the Ubuntu PPA. 2.2.1 worked flawlessly.

I installed the old from the cache and did `apt-mark hold ansible` for the moment.

**Comment by bcoca** [comment]
This affects  2.2.1 and 2.2.2 as the patch did not make it into the tree in time for release, it will be included in the next release (coming soon). Closing as fixed, but pending release.

**Comment by BillRainford** [comment]
When is the next release coming out?

**Comment by ssbarnea** [comment]
I am quite curious about the same thing and also wondering how it happened that this was not catched earlier in the process. I am encountering is even on most masic ansible setups.

**Comment by ppar** [comment]
Regarding the Ubuntu PPA packages, 2.2.1 is already gone from the apt repo but it's archived here:

https://launchpad.net/~ansible/+archive/ubuntu/ansible/+sourcepub/7405318/+listing-archive-extra

To roll back, do:

```
# curl -LO https://launchpad.net/~ansible/+archive/ubuntu/ansible/+files/ansible_2.2.1.0-1ppa~trusty_all.deb
# dpkg -i ansible_2.2.1.0-1ppa~trusty_all.deb
```

**Comment by Jalle19** [comment]
I've had to switch to the `ansible/ansible-2.1` PPA for all newly built machines since the latest version is currently unusable. Any ETA on a new release?

**Comment by e-alfred** [comment]
@ppar You still have to put the package on hold, otherwise it will be updated as soon as you install updates again.

**Comment by b-long** [comment]
@robkorv I think you may have mistakenly forgot an equal sign.  I believe this should be : 

```
pip install ansible==2.2.1.0
```
I'm no Python expert, but it may help others who stumble upon this issue and thanks for providing the tip in the first place! 😃

**Comment by cadavre** [comment]
You have 22k+ stars, imagine how many people are using ansible. And a bug like this? :/

**Comment by omgjlk** [comment]
This bug only impacts inventories that have ungrouped hosts. Simply putting your hosts into a group will work around the bug.

It's frustrating, sure, but it also shows a place where a new integration test could be added to Ansible. It also highlights an uncommon scenario, ungrouped hosts. Easy enough to work around at your site while waiting for a new release.

**Comment by bcoca** [comment]
its a bit more of a corner case its for 'grouped' hosts that were also incorrectly ungrouped due to the specific file parser (ini in this case). Which is what the patch tried to fix but created this break as it relied on a method that had not been backported. Tests did not hit it as no tests in the old branch have this case,  not in devel either, but it was my list to actually add it there.

**Comment by ssbarnea** [comment]
@j2sol I really doubt that ungrouped hosts is such an uncommon scenario: for example I know lots of projects that do with a default "hosts" file that contains only localhost, allowing tests of that repository to run without further configuration.

I think that almost all projects involving Ansible that would run on Travis or something similar would need this.

**Comment by bcoca** [comment]
@ssbarnea read my blurb above, its not just 'ungrouped' they also have to be grouped and incorrectly left in the 'ungrouped' group.

**Comment by rss2403** [comment]
Indeed. This seems to work just fine:

```
[all]
test-bastion ansible_ssh_host=127.0.0.1 ansible_ssh_user=ubuntu

[bastion]
test-bastion
```

This doesn't:

```
test-bastion ansible_ssh_host=127.0.0.1 ansible_ssh_user=ubuntu

[bastion]
test-bastion
```

**Comment by pablodav** [comment]
If you are using molecule for testing you must move to `2.2.1` until `2.2.3` is released. 

see https://github.com/metacloud/molecule/issues/783 

The issue is because molecule creates an inventory with hosts in empty group, example: 

```
cat .molecule/ansible_inventory 
ansible_burp2_server-01 ansible_connection=docker
ansible_burp2_server-master2 ansible_connection=docker
ansible_burp2_server-03 ansible_connection=docker

[group_master]
ansible_burp2_server-master2

[groupa]
ansible_burp2_server-01
ansible_burp2_server-03
```

**Comment by retr0h** [comment]
I released a new version of molecule (1.23.1) to address this issue.

Also, appears this is not an issue, if using the yaml syntax of ansible inventory.

```
---
ungrouped:
  hosts:
    instance-1-default:
      ansible_connection: docker
  vars:
    molecule_file: /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/molecule.yml
    molecule_instance_config: /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/.molecule/instance_config.yml
    molecule_inventory_file: /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default/.molecule/ansible_inventory.yml
    molecule_scenario_directory: /Users/jodewey/git/molecule_2/test/scenarios/driver/docker/molecule/default
```

**Comment by simonszu** [comment]
@retr0h The more you know - i didn't know it was possible to create the inventoriy in YAML, always did it in ini-style. So, double thumbs up.
