### ISSUE TITLE
Enable lookup plugins to reference files within a role directory unqualified.

### ISSUE THREAD

**Issue by cmhamill** [ansible/ansible#2697]
So that:

```
- debug: msg={{ lookup('file', 'foo.txt') }}
```

will work if 'foo.txt' is in 'roles/rolename/files' or in the normal basedir.

Not sure how best to implement this, but I'd be happy to do the work if there are suggestions.

**Comment by mpdehaan** [comment]
Fixed in b8a66ce

Any included file will now look relative to itself in lookup plugins, or in the case of roles, if a 'files' directory exists in the role it will look there.

Should do exactly what you want here.

**Comment by gw0** [comment]
Probably because of this change I am experiencing the following issues in latest development version (around 1 month ago things like this worked):

```
#playbook.yml
---
- hosts: all
  gather_facts: no
  vars:
    testaa: $FILE('testbb/files/testaa')
    #testaa: $FILE('../../testbb/files/testaa')
  roles:
    - testbb
  tasks:
    - shell: echo "in task {{ testaa }}"
```

```
#testbb/tasks/main.yml
---
- shell: echo "in role {{ testaa }}"
```

Now I either get:

```
ERROR: /home/xxx/testbb/files/testbb/files/testaa does not exist
or
ERROR: /testbb/files/testaa does not exist
```

This is a simplified case that fails. Originally I am using this the file lookup plugin inside a variable in group_vars and want it to be available in all roles, tasks and templates. (Also check the situation when using such a variable inside templates after the above is fixed.)

**Comment by mpdehaan** [comment]
I was able to use the file plugin successfully, do you already have a directory in your current directory named "files" or something?  If so, it will dive in and try to use that directory, but if not, it will not.

**Comment by gw0** [comment]
I created an empty directory with a fresh ansible installation and the problem persists:

```
$ mkdir xx; cd xx; virtualenv --no-site-packages venv; . venv/bin/activate
$ pip install git+https://github.com/ansible/ansible.git
```

```
# testbb/tasks/main.yml
---
- shell: echo "in role {{ foo }}"
- template: src=tmpl.j2 dest=/tmp/test_tmpl
- shell: cat /tmp/test_tmpl
```

```
# testbb/files/foo
this is foo file
```

```
# testbb/templates/tmpl.j2
Test template {{ foo }}
```

Various cases:

```
$ cat playbook1.yml 
# playbook1.yml
---
- hosts: all
  gather_facts: no
  vars:
    foo: $FILE('foo')
$ ansible-playbook -i hosts -u root -v playbook1.yml 
ERROR: /home/aaa/xx/foo does not exist
```

```
$ cat playbook2.yml 
# playbook2.yml
---
- hosts: all
  gather_facts: no
  vars:
    foo: $FILE('testbb/files/foo')
  roles:
    - testbb
  tasks:
    - shell: echo "in task {{ foo }}"
$ ansible-playbook -i hosts -u root -v playbook2.yml 

PLAY [all] ******************************************************************** 
ERROR: /home/aaa/xx/testbb/files/testbb/files/foo does not exist
```

```
 cat playbook3.yml 
# playbook3.yml
---
- hosts: all
  gather_facts: no
  vars:
    foo: $FILE('../../testbb/files/foo')
  roles:
    - testbb
$ ansible-playbook -i hosts -u root -v playbook3.yml 
ERROR: /home/testbb/files/foo does not exist
```

As you can see the only `files` directory is inside `testbb` role. How to make a playbook with all the above options work (that the same variable with file lookup plugin can be used inside a task in a role, in the template inside a role, in playbook under vars or in inventory group_vars, in a normal task in the playbook)?

Imho the solution should be that the lookup order for the file plugin should be in that order:
- use absolute path, if starting with "/"
- check relative to roles files directory, if used in role
- check relative to template, if used inside a template
- check relative to tasks file, if used in a tasks file (maybe creck relative to each one in hierarchy of include statements?)
- check relative to playbook
- check relative to inventory file (this is also useful if you want it relative to group_vars)

**Comment by gw0** [comment]
This is still relevant issue for latest development version. Should I put it in a new ticket?

**Comment by hugomrdias** [comment]
still having problems with this

```
# file roles/vhost/tasks/main.yml
---
  - name: vhost | add php5-fpm "{{ vhost.name }}" pool
    template: src={{ item }} dest=/etc/php5/fpm/pool.d/{{ vhost.name }}.conf mode=0644
    first_available_file:
      - pool.conf.{{ inventory_hostname }}.j2
      - pool.conf.js
    notify:
      - restart php5-fpm
    tags: vhost
```

throws :

```
fatal: [vagrant.dev] => {'msg': 'could not find src in first_available_file list', 'failed': True}
fatal: [vagrant.dev] => {'msg': 'could not find src in first_available_file list', 'failed': True}

FATAL: all hosts have already failed -- aborting
```

im running ansible from a checkout

**Comment by gw0** [comment]
Maybe because of a typo: `pool.conf.js` != `pool.conf.j2`?
