### ISSUE TITLE
"unable to open shell" error when host not in .ssh/known_hosts in network modules

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#27136]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- lib/ansible/modules/network
- ansible-connection

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel f58a0cb2b9) last updated 2017/07/20 15:20:44 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT

MacOS Sierra

##### SUMMARY

Attempting to run network tasks on network devices that aren't in .ssh/known_hosts causes an "unable to open shell" error.

##### STEPS TO REPRODUCE

- SSH into a device (in order to ensure it is in known hosts)
- Run a playbook against it such as `ansible-playbook -i inventory.network -u vyos -k vyos.yaml -e limit_to=vyos_command`
- Delete the entry for the host from known_hosts
- Wait 30 seconds (for the previous connection to die)
- Run the playbook again

The second time it should fail.

```yaml

```

##### EXPECTED RESULTS

Not sure what the correct way to handle hosts missing from known_hosts is for network devices. 

##### ACTUAL RESULTS

```
TASK [vyos_command : test contains operator] *********************************************************************************************************************************************************************************************************************************
fatal: [vyos02]: FAILED! => {"changed": false, "failed": true, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}
```

**Comment by newswangerd** [comment]
adding PARAMIKO_HOST_KEY_AUTO_ADD=true doesn't as suggested by [this commit](https://github.com/ansible/ansible/pull/18598/commits/aac1d8ea3d7fd7caca127d7c5a999fad2ffe669f) doesn't seen to work.

`PARAMIKO_HOST_KEY_AUTO_ADD=true ansible-playbook -i inventory.network -u vyos -k vyos.yaml -e limit_to=vyos_command`

```
TASK [vyos_command : test contains operator] *********************************************************************************************************************************************************************************************************************************
fatal: [vyos02]: FAILED! => {"changed": false, "failed": true, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}
```

**Comment by newswangerd** [comment]
Possible solutions for this:
* Fix PARAMIKO_HOST_KEY_AUTO_ADD and add it to the docs so that people know it exists
* Improve error reporting for the "unable to open shell" error with more precise error messages for:
  * invalid credentials
  * the host isn't in known hosts
  * the host is unreachable
  * Ansible can't enter config mode on the device

**Comment by newswangerd** [comment]
ANSIBLE_HOST_KEY_CHECKING=false fixes this.

**Comment by newswangerd** [comment]
closed because PARAMIKO_HOST_KEY_AUTO_ADD was fixed for network modules

**Comment by jurajbgh** [comment]
hi all how do ai apply the fix?
thanks.

**Comment by newswangerd** [comment]
@jurajbgh You can either ssh into the device first and select to have the host added to the known hosts file, or you can add the ANSIBLE_HOST_KEY_CHECKING=false environment variable before you run the playbook.

**Comment by jurajbgh** [comment]
@newswangerd  hello sir, I did the first step, the ssh but still the same issue, the second option wil this be in the ansible.cfg? Thanks!!!

**Comment by jugatsu** [comment]
@jurajbgh
```bash
ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook playbook.yml
```
or add to ansible.cfg
`host_key_checking = False`

**Comment by jurajbgh** [comment]
thanks the issue was fixed!

**Comment by keerthana-sargunam** [comment]
Hii,
 
I am running the playbook configure.yml to configure the ipaddress in the cisco router,but it shows "unable to open shell" error.
This is my playbook configure.yml
---
 - name: Cisco interface config
   connection: local
   hosts: 10.1.0.144
   gather_facts: true
   vars:
     cli:
       username: {admin}
       password: {admin}
       host: 10.1.0.144
   tasks:
     - name: configure IP address
       ios_config:

         before:
           - default interface gigabitEthernet2
         command:
           - ip address 192.168.255.77 255.255.255.0
         after:
           - no shut
         provider: { cli }
         match: strict
         parents: interface gigabitEthernet2

Error:TASK [configure IP address] ****************************************************
fatal: [10.1.0.100]: FAILED! => {"changed": false, "failed": true, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}



Can anyone help me to solve this?

**Comment by jurajbgh** [comment]
Hello,
can you test ssh -l user ip ? do you have access? what version of ansible are you working with? instead of using , can you try with the direct user/pass? 
vars:
cli:
username: {admin}
password: {admin}

**Comment by keerthana-sargunam** [comment]
@jurajbgh-Tried to acess by the command,
ssh username@ip
 ssh admin@10.1.0.100
Password:

CSR1000v#
CSR1000v#
CSR1000v#
CSR1000v#sh ip int br
Interface              IP-Address      OK? Method Status                Protocol
GigabitEthernet1       10.1.0.100      YES NVRAM  up                    up
GigabitEthernet2       192.168.255.66  YES NVRAM  up                    up
GigabitEthernet3       unassigned      YES NVRAM  administratively down down


My ansible version is 2.4.1.0 and even i tried with direct username and password

**Comment by jurajbgh** [comment]
After you did that, you are still with the same issue. can you post you ansible.cfg please.

**Comment by keerthana-sargunam** [comment]
### # config file for ansible -- https://ansible.com/
# ===============================================

# nearly all parameters can be overridden in ansible-playbook
# or with command line flags. ansible will read ANSIBLE_CONFIG,
# ansible.cfg in the current working directory, .ansible.cfg in
# the home directory or /etc/ansible/ansible.cfg, whichever it
# finds first

[defaults]
host_Key_checking = False


# some basic default values...

#inventory      = /etc/ansible/hosts
#library        = /usr/share/my_modules/
#module_utils   = /usr/share/my_module_utils/
#remote_tmp     = ~/.ansible/tmp
host_Key_checking = False


# some basic default values...

#inventory      = /etc/ansible/hosts
#library        = /usr/share/my_modules/
#module_utils   = /usr/share/my_module_utils/
#remote_tmp     = ~/.ansible/tmp
#local_tmp      = ~/.ansible/tmp
#forks          = 5
#poll_interval  = 15
#sudo_user      = root
#ask_sudo_pass = True
#ask_pass      = True
#transport      = smart
#remote_port    = 22
#module_lang    = C
#module_set_locale = False
# plays will gather facts by default, which contain information about
# the remote system.
#
# smart - gather by default, but don't regather if already gathered
# implicit - gather by default, turn off with gather_facts: False
# explicit - do not gather by default, must say gather_facts: True
#gathering = implicit

# This only affects the gathering done by a play's gather_facts directive,
 by default gathering retrieves all facts subsets
# all - gather all subsets
# network - gather min and network facts
# hardware - gather hardware facts (longest facts to retrieve)
# virtual - gather min and virtual facts
# facter - import facts from facter
# ohai - import facts from ohai
# You can combine them using comma (ex: network,virtual)
# You can negate them using ! (ex: !hardware,!facter,
# A minimal set of facts is always gathered.
#gather_subset = all

# some hardware related facts are collected
# with a maximum timeout of 10 seconds. This
# option lets you increase or decrease that
# timeout to something more suitable for the
# environment.
# gather_timeout = 10

# additional paths to search for roles in, colon separated
#roles_path    = /etc/ansible/roles

# uncomment this to disable SSH key host checking
#host_key_checking = False

# change the default callback, you can only have one 'stdout' type  enabled at$
#stdout_callback = skippy


## Ansible ships with some plugins that require whitelisting,
## this is done to avoid running all of a type by default.
## These setting lists those that you want enabled for your system.
## Custom plugins should not need this unless plugin author specifies it.

# enable callback plugins, they can output to stdout but cannot be 'stdout' ty$
#callback_whitelist = timer, mail

# Determine whether includes in tasks and handlers are "static" by
# default. As of 2.0, includes are dynamic by default. Setting these
# values to True will make includes behave more like they did in the
# 1.x versions.
#task_includes_static = True
#handler_includes_static = True

# Controls if a missing handler for a notification event is an error or a warn$
#error_on_missing_handler = True

# change this for alternative sudo implementations
#sudo_exe = sudo
# What flags to pass to sudo
# WARNING: leaving out the defaults might create unexpected behaviours
#sudo_flags = -H -S -n

# SSH timeout
#timeout = 10

# default user to use for playbooks if user is not specified
# (/usr/bin/ansible will use current user as default)
#remote_user = root
# logging is off by default unless this path is defined
# if so defined, consider logrotate
#log_path = /var/log/ansible.log

# default module name for /usr/bin/ansible
#module_name = command

# use this shell for commands executed under sudo
# you may need to change this to bin/bash in rare instances
# if sudo is constrained
#executable = /bin/sh

# if inventory variables overlap, does the higher precedence one win
# or are hash values merged together?  The default is 'replace' but
# this can also be set to 'merge'.
#hash_behaviour = replace

# by default, variables from roles will be visible in the global variable
# scope. To prevent this, the following option can be enabled, and only
# tasks and handlers within the role will see the variables there
#private_role_vars = yes

# list any Jinja2 extensions to enable here:
#jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n

# if set, always use this private key file for authentication, same as
# if passing --private-key to ansible or ansible-playbook
#private_key_file = /path/to/file
# If set, configures the path to the Vault password file as an alternative to
# specifying --vault-password-file on the command line.
#vault_password_file = /path/to/vault_password_file

# format of string {{ ansible_managed }} available within Jinja2
# templates indicates to users editing templates files will be replaced.
# replacing {file}, {host} and {uid} and strftime codes with proper values.
#ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {u$
# {file}, {host}, {uid}, and the timestamp can all interfere with idempotence
# in some situations so the default is a static string:
# by default, ansible-playbook will display "Skipping [host]" if it determines$
# should not be run on a host.  Set this to "False" if you don't want to see t$
# messages. NOTE: the task header will still be shown regardless of whether or$
# task is skipped.
#display_skipped_hosts = True

# by default, if a task in a playbook does not include a name: field then
# ansible-playbook will construct a header that includes the task's action but
 not the task's args.  This is a security feature because ansible cannot know
# if the *module* considers an argument to be no_log at the time that the
# header is printed.  If your environment doesn't have a problem securing
# stdout from ansible-playbook (or you have manually specified no_log in your
# playbook on all of the tasks where you have secret information) then you can
# safely set this to True to get more informative messages.
#display_args_to_stdout = False

# by default (as of 1.3), Ansible will raise errors when attempting to derefer$
# Jinja2 variables that are not set in templates or action lines. Uncomment th
# to revert the behavior to pre-1.3.
#error_on_undefined_vars = False

# by default (as of 1.6), Ansible may display warnings based on the configurat$
# system running ansible itself. This may include warnings about 3rd party pac$
# other conditions that should be resolved if possible.
# to disable these warnings, set the following value to False:
#system_warnings = True

# by default (as of 1.4), Ansible may display deprecation warnings for language
# features that should no longer be used and will be removed in future version$
# to disable these warnings, set the following value to False:
#deprecation_warnings = True

# (as of 1.8), Ansible can optionally warn when usage of the shell and
# command module appear to be simplified by using a default Ansible module
# instead.  These warnings can be silenced by adjusting the following
# setting or adding warn=yes or warn=no to the end of the command line
# parameter string.  This will for example suggest using the git module
# instead of shelling out to the git command.
# set plugin path directories here, separate with colons
#action_plugins     = /usr/share/ansible/plugins/action
#cache_plugins      = /usr/share/ansible/plugins/cache
#callback_plugins   = /usr/share/ansible/plugins/callback
#connection_plugins = /usr/share/ansible/plugins/connection
#lookup_plugins     = /usr/share/ansible/plugins/lookup
#inventory_plugins  = /usr/share/ansible/plugins/inventory

vars_plugins       = /usr/share/ansible/plugins/vars
#filter_plugins     = /usr/share/ansible/plugins/filter
#test_plugins       = /usr/share/ansible/plugins/test
#terminal_plugins   = /usr/share/ansible/plugins/terminal
#strategy_plugins   = /usr/share/ansible/plugins/strategy


# by default, ansible will use the 'linear' strategy but you may want to try
# another one
#strategy = free
# set which cowsay stencil you'd like to use by default. When set to 'random',
# a random stencil will be selected for each task. The selection will be filte$
# against the `cow_whitelist` option below.
#cow_selection = default
#cow_selection = random

# when using the 'random' option for cowsay, stencils will be restricted to th$
# it should be formatted as a comma-separated list with no spaces between name$
# NOTE: line continuations here are for formatting purposes 
#       in python does not support them.
#cow_whitelist=bud-frogs,bunny,cheese,daemon,default,dragon,elephant-in-snake,$
#              hellokitty,kitty,luke-koala,meow,milk,moofasa,moose,ren,sheep,s$
#              stimpy,supermilker,three-eyes,turkey,turtle,tux,udder,vader-koa$

# don't like colors either?
# set to 1 if you don't want colors, or export ANSIBLE_NOCOLOR=1
#nocolor = 1

# if set to a persistent type (not 'memory', for example 'redis') fact values
# from previous runs in Ansible will be stored.  This may be useful when
# wanting to use, for example, IP information from one group of servers
# without having to talk to them in the same playbook run to get their
# current IP information.
#fact_caching = memory

# set which cowsay stencil you'd like to use by default. When set to 'random',
# a random stencil will be selected for each task. The selection will be filte$
# against the `cow_whitelist` option below.
#cow_selection = default

# when using the 'random' option for cowsay, stencils will be restricted to th$
# it should be formatted as a comma-separated list with no spaces between name$
# NOTE: line continuations here are for formatting purposes only, as the INI p$
#       in python does not support them.
#cow_whitelist=bud-frogs,bunny,cheese,daemon,default,dragon,elephant-in-snake,$
#              hellokitty,kitty,luke-koala,meow,milk,moofasa,moose,ren,sheep,s$
#              stimpy,supermilker,three-eyes,turkey,turtle,tux,udder,vader-koa$

# don't like colors either?
# set to 1 if you don't want colors, or export ANSIBLE_NOCOLOR=1
#nocolor = 1

# if set to a persistent type (not 'memory', for example 'redis') fact values

# retry files
# When a playbook fails by default a .retry file will be created in ~/
# You can disable this feature by setting retry_files_enabled to False
# and you can change the location of the files by setting retry_files_save_path

retry_files_enabled = False
#retry_files_save_path = ~/.ansible-retry

# squash actions
# Ansible can optimise actions that call modules with list parameters
# when looping. Instead of calling the module once per with_ item, the
# module is called once with all items at once. Currently this only works
# under limited circumstances, and only with parameters named 'name'.
#squash_actions = apk,apt,dnf,homebrew,pacman,pkgng,yum,zypper

#no_log = False

# prevents logging of tasks, but only on the targets, data is still logged on $
#no_target_syslog = False

# controls whether Ansible will raise an error or warning if a task has no
# choice but to create world readable temporary files to execute a module on
# the remote machine.  This option is False by default for security.  Users may

# https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
# for more secure ways to fix this than enabling this option.
#allow_world_readable_tmpfiles = False

# controls the compression level of variables sent to
# worker processes. At the default of 0, no compression
# is used. This value must be an integer from 0 to 9.
#var_compression_level = 9

# controls what compression method is used for new-style ansible modules when
# they are sent to the remote system.  The compression types depend on having
# support compiled into both the controller's python and the client's python.
# The names should match with the python Zipfile compression types:
# * ZIP_STORED (no compression. available everywhere)
# * ZIP_DEFLATED (uses zlib, the default)
# These values may be set per host via the ansible_module_compression inventory
# variable
#module_compression = 'ZIP_DEFLATED'

# This controls the cutoff point (in bytes) on --diff for files
# set to 0 for unlimited (RAM may suffer!).
#max_diff_size = 1048576

# This controls how ansible handles multiple --tags and --skip-tags arguments
# on the CLI.  If this is True then multiple arguments are merged together.  If
# it is False, then the last specified argument is used and the others are ign$
# This option will be removed in 2.8.
#merge_multiple_cli_flags = True
# Controls which files to ignore when using a directory as inventory with
# possibly multiple sources (both static and dynamic)
#inventory_ignore_extensions = ~, .orig, .bak, .ini, .cfg, .retry, .pyc, .pyo

# This family of modules use an alternative execution path optimized for netwo$
# only update this setting if you know how this works, otherwise it can break $
#network_group_modules=['eos', 'nxos', 'ios', 'iosxr', 'junos', 'vyos']

# When enabled, this option allows lookups (via variables like {{lookup('foo')$
# a loop with `with_foo`) to return data that is not marked "unsafe". This mea$
# jinja2 templating language which will be run through the templating engine.
# ENABLING THIS COULD BE A SECURITY RISK
#allow_unsafe_lookups = False

# set default errors for all plays
#any_errors_fatal = False
# enable inventory plugins, default: 'host_list', 'script', 'yaml', 'ini'
#enable_plugins = host_list, virtualbox, yaml, constructed

# ignore these extensions when parsing a directory as inventory source
#ignore_extensions = .pyc, .pyo, .swp, .bak, ~, .rpm, .md, .txt, ~, .orig, .in$

# ignore files matching these patterns when parsing a directory as inventory s$
#ignore_patterns=

# If 'true' unparsed inventory sources become fatal errors, they are warnings $
#unparsed_is_failed=False

[privilege_escalation]
#become=True
#become_method=sudo
#become_user=root
#become_ask_pass=False

[paramiko_connection]

**Comment by Slake66** [comment]
Hi,
i have a similar problem when i run the playbook:

  ```
hosts: switches
  gather_facts: yes
  connection: local

  vars_prompt:
    - name: "some_username"
      prompt: "Enter Username"
      private: no

    - name: "my_password"
      prompt: "Enter password"
      private: yes
      confirm: yes

    - name: "enable_password"
      prompt: "Enter Priviledge password"
      private: yes
      confirm: yes

  tasks:


  - name: DEFINE PROVIDER
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ some_username }}"
        password: "{{ my_password }}"
        auth_pass: "{{ enable_password}}"

  - name: RUN 'show version'
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show version | incl image
        - show version | incl uptime
    register: version


  - name: "Ansible date fact"
    debug:
      var=ansible_date_time.date

  - debug: var=version.stdout_lines
```

this error pops up:

PLAY [switches] *****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [x.x.x.x]

TASK [DEFINE PROVIDER] **********************************************************************************************************************************************************************************************************************
ok: [x.x.x.x]

TASK [RUN 'show version'] *******************************************************************************************************************************************************************************************************************
fatal: [x.x.x.x]: FAILED! => {"changed": false, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}
        to retry, use: --limit @/home/thomas_test/show_version.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
x.x.x.x               : ok=2    changed=0    unreachable=0    failed=1





the switch says:

%SSH-4-SSH2_UNEXPECTED_MSG: Unexpected message type has arrived. Terminating the connection from x.x.x.x
