### ISSUE TITLE
Ansible 2.4 CallBackModule error?

### ISSUE THREAD

**Issue by smuthali** [ansible/ansible#30597]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- CallBackModule
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0.0
  config file = /Users/<REDACTED>/ansible.cfg
  configured module search path = [u'/Users/<REDACTED>/ansible-lib/library']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Aug  7 2017, 22:02:14) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.28.1)]
```

##### CONFIGURATION
```
ANSIBLE_SSH_CONTROL_PATH(/Users/<REDACTED>/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_PIPELINING(/Users/<REDACTED>/ansible.cfg) = False
DEFAULT_ACTION_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/Users/<REDACTED>/ansible.cfg) = ['log_plays_capture', 'mail', 'actionable', 'skippy', 'task_timer', 'version_recorder']
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/filter']
DEFAULT_HASH_BEHAVIOUR(/Users/<REDACTED>/ansible.cfg) = merge
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/lookup_plugins']
DEFAULT_MODULE_PATH(/Users/<REDACTED>/ansible.cfg) = [u'/Users/<REDACTED>/ansible-lib/library']
DEFAULT_REMOTE_TMP(/Users/<REDACTED>/ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_STDOUT_CALLBACK(/Users/<REDACTED>/ansible.cfg) = skippy
DEFAULT_TRANSPORT(/Users/<REDACTED>/ansible.cfg) = smart
DEPRECATION_WARNINGS(/Users/<REDACTED>/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/Users/<REDACTED>/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/<REDACTED>/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A362a
```

##### SUMMARY
After upgrading from Ansible 2.3.2 to Ansible 2.4.0.0 (via pip2), We have a bunch of custom libraries, plugins (action, filter and lookup); I see exceptions in playbook runs.

```
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 90, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 203, in load_callbacks
    callback_obj .set_options(C.config.get_plugin_options('callback', callback_plugin._load_name))
AttributeError: 'CallbackModule' object has no attribute 'set_options'

```

##### ACTUAL RESULTS

```
  $ ansible-playbook -i env/qa -u <REDACTED> provision.yml --extra-vars="state=reloaded release=e4" --ask-become-pass --become --become-user=<REDACTED> --vault-password-file=~/.vault_pass --limit=<REDACTED> -vvvv
  ansible-playbook 2.4.0.0
    config file = /Users/<REDACTED>/ansible.cfg
    configured module search path = [u'/Users/<REDACTED>/ansible-lib/library']
    ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
    executable location = /usr/local/bin/ansible-playbook
    python version = 2.7.13 (default, Aug  7 2017, 22:02:14) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.28.1)]
  Using /Users/<REDACTED>/ansible.cfg as config file
  SUDO password:
  setting up inventory plugins
  Parsed /Users/<REDACTED>/env/qa/inventory inventory source with ini plugin
  Loading callback plugin skippy of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
  ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'
  the full traceback was:

  Traceback (most recent call last):
    File "/usr/local/bin/ansible-playbook", line 106, in <module>
      exit_code = cli.run()
    File "/usr/local/lib/python2.7/site-packages/ansible/cli/playbook.py", line 130, in run
      results = pbex.run()
    File "/usr/local/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 90, in run
      self._tqm.load_callbacks()
    File "/usr/local/lib/python2.7/site-packages/ansible/executor/task_queue_manager.py", line 203, in load_callbacks
      callback_obj .set_options(C.config.get_plugin_options('callback', callback_plugin._load_name))
  AttributeError: 'CallbackModule' object has no attribute 'set_options'
```

**Comment by drybjed** [comment]
I can confirm that I get a similar error running Ansible 2.4 built from `git` source tree, on Debian Jessie host:
```
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 90, in run
    self._tqm.load_callbacks()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 203, in load_callbacks
    callback_obj .set_options(C.config.get_plugin_options('callback', callback_plugin._load_name))
AttributeError: 'CallbackModule' object has no attribute 'set_options'
```

**Comment by ralphie02** [comment]
I get the exact same error traceback on Ubuntu 16.04. Anyone has a workaround or just downgrade for now?

**Comment by bcoca** [comment]
PR above should fix this, I had not expected callbacks that did not inherit from base, directly or indirectly.

**Comment by smuthali** [comment]
As @bcoca mentioned, in your custom callback modules  ```CallbackBase ``` must be explicitly referenced, i.e. ``` from ansible.plugins.callback import CallbackBase ```

**Comment by drybjed** [comment]
@smuthali I added the line you mentioned to the custom [`profile_tasks` callback](https://github.com/debops/debops-playbooks/blob/master/playbooks/callback_plugins/profile_tasks.py) I use but the error is still present. Any idea what else needs to be changed for this to work?

**Comment by ralphie02** [comment]
I explicitly removed my callbacks from my `ansible.cfg` before I even commented and the issue is still reproducible.

before:
```
[defaults]
callback_whitelist = profile_tasks
callback_plugins = ~/ansible/callback_plugins
...
```
after
```
[defaults]
callback_whitelist = profile_tasks
...
```
unless this is not what is meant? If this is not the case, could someone please let me know?

**Comment by smuthali** [comment]
@drybjed and @ralphie02 -  This is what I did, excerpts from one of the custom CallBacks
```
from ansible.plugins.callback import CallbackBase  <-------- Here
try:
    imp.find_module('yaml')
    pass
except ImportError as e:
    logger.error("Unable to locate pyyaml python module")

class CallbackModule(CallbackBase): <-------------- Here
    CALLBACK_VERSION = 2.0
    CALLBACK_TYPE = 'version_recorder'
    CALLBACK_NAME = 'alt_version'
    CALLBACK_NEEDS_WHITELIST = True

    def __init__(self):
        super(CallbackModule, self).__init__()
```
Here's my ``` ansible.cfg ```
```
[defaults]
filter_plugins = ansible-lib/filter
callback_plugins = ansible-lib/callback_plugins
callback_whitelist = log_plays_capture, mail, actionable, skippy, task_timer, version_recorder
stdout_callback = skippy
action_plugins = ansible-lib/action_plugins
connection_plugins = ansible-lib/connection_plugins
library = ansible-lib/library
lookup_plugins = ansible-lib/lookup_plugins
fork = 500
deprecation_warnings=false
host_key_checking = false
hash_behaviour = merge
remote_tmp = $HOME/.ansible/tmp
transport = smart
display_skipped_hosts = False


[ssh_connection]
control_path = %(directory)s/%%h-%%r
pipelining = False

[filters]
vault_filter_key = ykpass_vault.key
vault_filter_salt = <REDACTED>
vault_filter_iterations = 1000000
vault_filter_generate_key = yes
```

**Comment by drybjed** [comment]
@smuthali Thanks, this did the trick. :+1:

**Comment by bcoca** [comment]
i updated developer and porting docs, feedback welcome

**Comment by ChristopherCorcoran** [comment]
Any chance you can get this fix uploaded to the ubuntu xenial repo? Or at least restore 2.3 in the meantime? Looks like the broken version is still out there:

https://launchpad.net/~ansible/+archive/ubuntu/ansible

**Comment by Borrelworst** [comment]
I do use the standard ansible.cfg without any custom plugins and still encounter this error:
[DEPRECATION WARNING]: default callback, does not support setting 'options', it will work for now,  but this will be required in the future and should be updated,  see the 2.4 porting guide for details.. 

I do not set any options, this error is there since upgrading to 2.4.2.0. Even when placing the rpmnew config in place I encounter this error, it is an 'out of the box' issue.

@smuthali You've set this in your config: deprecation_warnings=false, suppressing these messages. It looks like it is not fixed yet.

I would really help to not only show the warning but also the location of the plugin which is causing this error.

Edit:

It looks like it is within this function:
/usr/lib/python2.7/site-packages/anible/plugins/callback/\__init\__.pyc
