### ISSUE TITLE
possible regression in templates after tag v1.2.3

### ISSUE THREAD

**Issue by sstark** [ansible/ansible#4030]
With the current devel branch the following template stopped working, which works fine with v1.2.3. "Stopped working" means hostvars.keys() is empty, rendering an almost empty template in that case:

  # {{ ansible_managed }}
  # vim: filetype=python:

  ipaddresses.update({
  {% for h in hostvars.keys() %}
      "{{ h }}": "{{ hostvars[h]['ansible_default_ipv4']['address'] }}",
  {% endfor %}
  })

  all_hosts += [ 
  {% for h in hostvars.keys() %}
  {% set tags = hostvars[h]['check_mk_tags'] %}
      "{{ h }}|agbs|{{ hostvars[h]['ansible_system'].lower().replace(' ', '') }}{{ '|'+'|'.join(tags) if tags }}",
  {% endfor %}
  ]

  extra_host_conf["alias"] += [
  {% for h in hostvars.keys() %}
      ( '{{ hostvars[h]['descr'] }}', ['{{ h }}'], ),
  {% endfor %}
  ]

**Comment by sstark** [comment]
The corresponding playbook for this is:

<pre>
  - name: collect facts
    hosts: all:!workstations
                                                                                                                                                                                                                   
  - hosts: sambesi
    gather_facts: no
    user: root
    tasks:
      - name: assemble check_mk config
        action: template src=ei-auto.mk.j2 dest=/etc/nagios3/check_mk/conf.d/ei-auto.mk mode=0644
        delegate_to: nagios
        register: check_mk_config
      - name: update nagios
        action: shell cmk -O
        delegate_to: nagios
        when: check_mk_config.changed
</pre>

**Comment by jimi-c** [comment]
I am able to reproduce this, taking a look at it now.

**Comment by jimi-c** [comment]
This should be fixed now, let me know if you continue to have problems with it.

**Comment by sstark** [comment]
Thanks for looking at this, but unfortunately it's not quite working yet: When I execute given playbook with

  ansible-playbook -vvv check_mk/gen_check_mk_config.yml

I get the output below. I have set check_mk_tags in host_vars/sambesi. The reason for the problem seems to be that the task is executed in another play on host sambesi with "gather_facts: no", which seems to overwrite the variables for it with an empty set. This has worked before.

TASK: [assemble check_mk config] *********************************************\* 
<nagios> ESTABLISH CONNECTION FOR USER: root
<nagios> EXEC ['ssh', '-tt', '-q', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/tmp/ansible-ssh-%h-%p-%r', '-o', 'Port=22', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', 'nagios', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1378473178.83-137844596323531 && echo $HOME/.ansible/tmp/ansible-1378473178.83-137844596323531'"]
fatal: [sambesi] => {'msg': "One or more undefined variables: 'dict object' has no attribute 'check_mk_tags'", 'failed': True}
fatal: [sambesi] => {'msg': "One or more undefined variables: 'dict object' has no attribute 'check_mk_tags'", 'failed': True}

FATAL: all hosts have already failed -- aborting

Sebastian

**Comment by jimi-c** [comment]
That appears to be a valid error, and is caused by the values being undefined. If you add `error_on_undefined_vars = False` to your ansible.cfg it will process the template normally (this is a change in 1.3, where that flag is True by default).

**Comment by sstark** [comment]
I have set check_mk_tags to the empty list in group_vars/all. In fact, if I set "error_on_undefined_vars = False" in ~/.ansible.cfg the error message about check_mk_tags not being defined still appears.

The playbook plays fine with ansible 1.2.3, I verified it once again.

**Comment by reedobrien** [comment]
The commit associated with this also breaks inventory parameter variables. The only one we tested was ansible_python_interpreter. But everything works fine on devel@ 2c27aa63 with only ae9e38d reverted.

given the following hosts file:

```
[local]
127.0.0.1 ansible_python_interpreter=../../bin/python
```

The correct interpreter and its packages are no longer found or used when ae9e38d in present.

**Comment by jimi-c** [comment]
So I'm reverting this all the way back to the way HostVars was originally, since that has apparently introduced too many side effects. Pushing this up now, so you guys should be able to retest shortly.

**Comment by reedobrien** [comment]
Thanks.

On Fri, Sep 6, 2013 at 9:18 PM, James Cammarata notifications@github.comwrote:

> So I'm reverting this all the way back to the way HostVars was originally,
> since that has apparently introduced too many side effects. Pushing this up
> now, so you guys should be able to retest shortly.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/4030#issuecomment-23978799
> .

## 

Reed O'Brien
Koansys, LLC
: reed@koansys.com
( 415-562-6797

**Comment by sstark** [comment]
I tried again yesterday with a current checkout, still my hostvars are empty for the second play in the given playbook.
