### ISSUE TITLE
lineinfile ignores newline “\n” in the line argument

### ISSUE THREAD

**Issue by jirutka** [ansible/ansible#5679]
I need to insert a multiline string with the _lineinfile_ module. According to [this article](http://fabian-affolter.ch/blog/the-lineinfile-module-of-ansible/), the special char `\n` should work, but in the current version it doesn’t.

```
lineinfile:
    dest=/tmp/file
    regexp='^MY_CONF='
    line='#some comment\nMY_CONF=value'
```

Result:

```
#some comment\nMY_CONF=value
```

Instead of:

```
#some comment
MY_CONF=value
```

Neither an actual new line doesn’t work:

```
lineinfile:
    dest=/tmp/file
    regexp='^MY_CONF='
    line='#some comment
          MY_CONF=value'
```

Result:

```
#some comment MY_CONF=value
```

**Comment by pierot** [comment]
I can confirm this behaviour

**Comment by spasche** [comment]
Is this supposed to work with the `line='#some comment\nMY_CONF=value'` syntax?

I tried with the devel branch of today, and I still get the same behavior you described initially.

If I use something like this:

```
  lineinfile:
    create=yes
    dest=/tmp/file
    regexp='^MY_CONF='
    line='#some comment\nMY_CONF=value'
```

and add a `print(repr(params['line']))` in library/files/lineinfile just before the re.sub, I see that the output is `'#some comment\\nMY_CONF=value'`, so the re.sub call doesn't convert the escaped newline.

**Comment by pierot** [comment]
In which release will this be working? I still encounter the same behaviour as described originally.

**Comment by jirutka** [comment]
This fix _was_ working, but it doesn’t work anymore. I’ve just pushed a new fix, see #6448 .

**Comment by jimi-c** [comment]
I've re-opened this due to the revert above, which was breaking other things (specifically backrefs).

**Comment by jirutka** [comment]
@jimi-c Could you please open a new issue and describe the problem, with examples if possible? I can’t understand what’s wrong from your comment, but it seems that it’s not about the problem described in this issue.

**Comment by jimi-c** [comment]
The issue is that when using decode(), things like `\1` are interpreted as octal escape sequences, causing things like the ^A in the output from #6821. We will use this issue to track the original problem, which was '\n' not being interpreted as newlines.

**Comment by jirutka** [comment]
I understand it now. So you’ve “solved” the issue #6821, without providing any test (!), by reverting the bugfix #6448 (along with a test)? Are you serious? Do you know what is testing about, especially regression testing?

**Comment by jimi-c** [comment]
I reverted your commit because it broke things in a very bad way (inserting control characters instead of a backref in a file is a very serious side-effect), and completely broke lineinfile function from 1.5.x->1.6. Obviously we want to fix the original issue, and when we do so we will have tests for both situations to ensure _neither_ use-case is broken.

**Comment by jimi-c** [comment]
I believe this patch will fix the issue, though it does work up to only 3 escapes (since python look-behinds must be a fixed-length): https://gist.github.com/jimi-c/79998638bfc48cc95338 (edited, github did not like that regex).

**Comment by jimi-c** [comment]
@jirutka I have created a pull request containing the above commit, if you'd like to test it before I merge it in. This includes your original test as well, plus one other test for backrefs that were broken before.

**Comment by disposable-ksa98** [comment]
I'm having this issue too.

**Comment by jimi-c** [comment]
I've merged in the fix above for this, which should resolve the issue. If you continue seeing problems related to this, please let us know. Thanks!

**Comment by fly-me** [comment]
This construction is now broken:
lineinfile: line="{{ item }}"
with_items: ["aa\nbb"]
I am getting single quotes in the result.

**Comment by jimi-c** [comment]
@fly-me could you please open a new issue for this? Thanks!

**Comment by den-is** [comment]
As I can see this issue still exists for ansible v 2.0.0 beta2

**Comment by abadger** [comment]
If you're experiencing these symptoms, please open a new bug with information on reproducing and your expectations of what should happen.  This bug has been closed which means that we're unlikely to see updates on it and that the code causing the issue this time is probably different.  If you do think that there's relevant information here (for instance, you suspect that the fix for this may have been reverted for some other reason) go ahead and link this report into the new bug report.

Thank you.
