### ISSUE TITLE
git module fails with "failed to stat '.': Permission denied"

### ISSUE THREAD

**Issue by yuriks** [ansible/ansible#6499]
##### Issue Type:

Bug report
##### Ansible Version:

`ansible-playbook 1.5.3`
##### Environment:

Both host and slave are running Ubuntu Server 12.04LTS
##### Summary:

This is the same issue as #6443 which doesn't seem to be fixed as of 1.5.3.

```
yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook --version
ansible-playbook 1.5.3
yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook -i yuriks.inventory site.yml

PLAY [glide-servers] **********************************************************

GATHERING FACTS ***************************************************************
ok: [provision]

[~~~snip~~~]

TASK: [cm | check out glide-cm] ***********************************************
failed: [provision] => {"cmd": ["/usr/bin/git", "ls-remote", "git@github.com:digEcor/glide-cm.git", "-h", "refs/heads/develop"], "failed": true, "item": "", "rc": 128}
stderr: fatal: failed to stat '.': Permission denied

msg: fatal: failed to stat '.': Permission denied

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/yuriks/site.retry

provision                  : ok=9    changed=0    unreachable=0    failed=1
```

The playbook is being run as root, but the git step has sudo and sudo_user fields to run as an unprivileged user. What seems to be happening is that the `git` command is being run with a cwd of `/root`, which isn't readable by the unprivileged user. Git tries to stat it and fails.
##### Steps To Reproduce:

Try to clone a new git repository using sudo.
##### Expected Results:

Cloning to succeed to the unprivileged user-owned directory.
##### Actual Results:

Git tries to read a directory it doens't have access to and aborts.

**Comment by mpdehaan** [comment]
Thanks, we'll take a look this very soon!

**Comment by jctanner** [comment]
@yuriks Can you show me the task from the playbook? 

I'm unable to reproduce based on my current understanding of the description:

```
- hosts: el6.lab.net
  #connection: local
  gather_facts: False
  user: jtanner
  tasks:
    - shell: whoami
    - shell: whoami
      sudo: True
    - shell: whoami
      sudo: True
      sudo_user: jtanner

    - git: repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/1
    - git: repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/2
      sudo: True
    - git: repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/3
      sudo: True
      sudo_user: jtanner
```

```
jtanner@u1204:~/issues/6499-git-path-sudo-fail$ ansible-playbook -v -i inventory site.yml

PLAY [el6.lab.net] ************************************************************

TASK: [shell whoami] **********************************************************
changed: [el6.lab.net] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.002198", "end": "2014-03-17 10:49:18.204074", "rc": 0, "start": "2014-03-17 10:49:18.201876", "stderr": "", "stdout": "jtanner"}

TASK: [shell whoami] **********************************************************
changed: [el6.lab.net] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.002212", "end": "2014-03-17 10:49:18.409052", "rc": 0, "start": "2014-03-17 10:49:18.406840", "stderr": "", "stdout": "root"}

TASK: [shell whoami] **********************************************************
changed: [el6.lab.net] => {"changed": true, "cmd": "whoami ", "delta": "0:00:00.002191", "end": "2014-03-17 10:49:18.644251", "rc": 0, "start": "2014-03-17 10:49:18.642060", "stderr": "", "stdout": "jtanner"}

TASK: [git repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/1] ***
ok: [el6.lab.net] => {"after": "badf58e9edd821f611387a0907d56c002453b249", "before": "badf58e9edd821f611387a0907d56c002453b249", "changed": false}

TASK: [git repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/2] ***
ok: [el6.lab.net] => {"after": "badf58e9edd821f611387a0907d56c002453b249", "before": "badf58e9edd821f611387a0907d56c002453b249", "changed": false}

TASK: [git repo=https://github.com/jctanner/ansible-pull-test  dest=/tmp/3] ***
ok: [el6.lab.net] => {"after": "badf58e9edd821f611387a0907d56c002453b249", "before": "badf58e9edd821f611387a0907d56c002453b249", "changed": false}

PLAY RECAP ********************************************************************
el6.lab.net                : ok=6    changed=3    unreachable=0    failed=0
```

**Comment by yuriks** [comment]
I can't, but I'll try to create a self-contained repro.

**Comment by yuriks** [comment]
Ah. For this to happen, user: needs to be root, so that `$HOME` is set to `/root`

**Comment by yuriks** [comment]
Repro playbook:

```
- hosts: provision
  user: root
  tasks:
    - git: repo=https://github.com/jctanner/ansible-pull-test dest=/home/digecor/ansible-pull-test
      sudo: True
      sudo_user: digecor
```

**Comment by jimi-c** [comment]
@yuriks this is fixed in devel as you noted, and we will included it in the next 1.5.x release. If you have any further questions regarding this, please let us know. Thanks!

**Comment by yuriks** [comment]
I thought that fix was supposed to have been included in 1.5.3? If it was not, then sorry for the misunderstanding.

**Comment by mpdehaan** [comment]
Correct, it is not in 1.5.3 -- 1.5.3 has already been released and this was reported after.

**Comment by yuriks** [comment]
The issue remains in 1.5.4:

```
yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook -i inventory.local test.yml

PLAY [glide-servers] **********************************************************

GATHERING FACTS ***************************************************************
ok: [digecor-cm]

TASK: [git repo=https://github.com/jctanner/ansible-pull-test dest=/home/xferuser/ansible-pull-test] ***
failed: [digecor-cm] => {"cmd": ["/usr/bin/git", "ls-remote", "https://github.com/jctanner/ansible-pull-test", "-h", "refs/heads/HEAD"], "failed": true, "rc": 128}
stderr: fatal: failed to stat '.': Permission denied

msg: fatal: failed to stat '.': Permission denied

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/yuriks/test.retry

digecor-cm                 : ok=1    changed=0    unreachable=0    failed=1

yuriks@glide-dev:~/src/glide-server/ansible$ ansible-playbook --version
ansible-playbook 1.5.4
```

Are there any plans to include this fix in 1.5? It renders the `git` module completely unusable for me.

**Comment by ashcrow** [comment]
I'm also hitting this same error in ansible 1.5.5.

**Comment by ghost** [comment]
Hi, 

same issue, ansible-1.5.5, happens if $HOME directory for ansible_ssh_user is set 0700 (umask 0077). The following playbook shows the issue.

Reproduce:

```
$ ansible_ssh_user=foo
$ sudo chmod 0700 /home/foo
$ ansible-playbook -i /path/to/your/inventory/file/with/localhost /path/to/playbook.yml
```



```
---
- hosts: localhost
  sudo: yes
  sudo_user: root
  vars:
    - git_user: foobar
    - git_repo: https://github.com/ansible/ansible
    - git_clone_base: /tmp/{{ git_user }}/repos
    - git_clone_repo: ansible
  tasks:
    - name: Create Git user
      user:
        home=/tmp/{{ git_user }}
        shell=/bin/bash
        name={{ git_user }}

    - name: Create Git clone base directory
      file:
        state=directory
        mode=0755
        owner={{ git_user }}
        dest={{ git_clone_base }}

    - name: Clone Git repository
      sudo: yes
      sudo_user: "{{ git_user }}"
      git:
        repo={{ git_repo }}
        dest={{ git_clone_base }}/{{ git_clone_repo }}
        force=yes
        remote=origin
        version=v1.5.5
```

To clean up the created user:

```
$ userdel --remove foobar # see {{ git_user }} above
```

**Comment by truptimali** [comment]
hi, I am also hitting the same issue . Has anyone found the resolution to this yet? Its not clear from the post whether its been resolved?

**Comment by mpz** [comment]
I am also have this issue.
fatal: failed to stat '.': Permission denied
