### ISSUE TITLE
Accented characters produce a UnicodeDecodeError when executing a playbook (ansible 1.5.3)

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#6655]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.5.3
```
##### Environment:
- Ubuntu 13.10
- Default terminal
- UTF8-encoded playbook file (default of Sublime Text 2)
##### Summary:

Accented characters produce a `UnicodeDecodeError` when executing a playbook.
##### Steps To Reproduce:

I was trying to run the following task in the only play of my playbook:

```
- command: git config --global user.name "Jérémie Astori"
```
##### Expected Results:

The playbook should run with no error and adds the corresponding line in the `.gitconfig` file.

If I replace the `é` by standard `e`s, the playbook is executed as expected and the `.gitconfig` file is properly updated.
##### Actual Results:

```
failed: [host] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "[...]/.ansible/tmp/ansible-tmp-1395677797.02-229460672953352/command", line 1304, in <module>
    main()
  File "[...]/.ansible/tmp/ansible-tmp-1395677797.02-229460672953352/command", line 90, in main
    module = CommandModule(argument_spec=dict())
  File "[...]/.ansible/tmp/ansible-tmp-1395677797.02-229460672953352/command", line 377, in __init__
    self._log_invocation()
  File "[...]/.ansible/tmp/ansible-tmp-1395677797.02-229460672953352/command", line 984, in _log_invocation
    syslog.syslog(syslog.LOG_NOTICE, unicode(msg).encode('utf8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 78: ordinal not in range(128)

FATAL: all hosts have already failed -- aborting
```

**Comment by jctanner** [comment]
@astorije this should be fixed in devel now. Please let me know otherwise.

**Comment by astorije** [comment]
@jctanner Thanks a lot for the quick answer! I am using distribution packages (Ubuntu), do you know when it will be available there?

**Comment by timruffles** [comment]
I just had the same crash, culprit was coloured output on `mkdir`:

```
(u'ecxxxxxx.eu-west-1.compute.amazonaws.com', 'Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p $HOME/.ansible/tmp/ansible-tmp-1403871746.71-145139516386871 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1403871746.71-145139516386871 && echo $HOME/.ansible/tmp/ansible-tmp-1403871746.71-145139516386871, exited with result 1: mkdir: cannot create directory \xe2\x80\x98/home/ubuntu/.ansible/tmp/ansible-tmp-1403871746.71-145139516386871\xe2\x80\x99: No space left on device\r\n')

Traceback (most recent call last):
File "/Users/imacuser/dev/ansible/bin/ansible-playbook", line 320, in <module>
  sys.exit(main(sys.argv[1:]))
File "/Users/imacuser/dev/ansible/bin/ansible-playbook", line 260, in main
  pb.run()
File "/Users/imacuser/dev/ansible/lib/ansible/playbook/__init__.py", line 323, in run
  if not self._run_play(play):
File "/Users/imacuser/dev/ansible/lib/ansible/playbook/__init__.py", line 677, in _run_play
  if not self._run_task(play, task, False):
File "/Users/imacuser/dev/ansible/lib/ansible/playbook/__init__.py", line 453, in _run_task
  results = self._run_task_internal(task)
File "/Users/imacuser/dev/ansible/lib/ansible/playbook/__init__.py", line 408, in _run_task_internal
  results = runner.run()
File "/Users/imacuser/dev/ansible/lib/ansible/runner/__init__.py", line 1228, in run
  results = [ self._executor(h, None) for h in hosts ]
File "/Users/imacuser/dev/ansible/lib/ansible/runner/__init__.py", line 535, in _executor
  self.callbacks.on_unreachable(host, msg)
File "/Users/imacuser/dev/ansible/lib/ansible/callbacks.py", line 465, in on_unreachable
  msg = "fatal: [%s] => %s" % (host, results)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 517: ordinal not in range(128)
```

**Comment by Gerst20051** [comment]
this is still happening with template files that have spanish characters
