### ISSUE TITLE
Variable interpolation in hostvars

### ISSUE THREAD

**Issue by ktosiek** [ansible/ansible#8213]
##### Summary:

When variables are accessed through hostvars, jinja2 expressions inside those variables should be interpolated.

There was discussion about this issue on ansible-project mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/pdWFR2Q8U8E/m6sgB1C5K1YJ

And here is a filter that shows simple implementation (but might be pretty slow, and I think it should be in hostvars not a filter): https://groups.google.com/group/ansible-project/attach/16318558e74073ae/hostvars.py?part=0.1&view=1
##### Steps To Reproduce:

Given vars like:

```
foo: y
bar: "x is {{ foo }}"
```

The values for both {{ bar }} and {{ hostvars[some_host].bar }} should be "x is y".
Currently the value of {{ hostvars[some_host].bar }} would be (literally) "x is {{ foo }}".

**Comment by jimi-c** [comment]
I'm pretty sure we can't do this for security reasons, since hostvars data might come from a remote script which would be somewhat insecure to allow.

**Comment by ktosiek** [comment]
That's exactly as secure as current situation - the same host vars are used when running play against that host, and they are going through interpolation.

**Comment by hughsaunders** [comment]
See also: https://github.com/ansible/ansible/issues/7844

**Comment by hughsaunders** [comment]
I am also seeing this issue in 1.8 and devel:

```
cb 0 (.venv) [devel 704f7d7] ~/git/ansible/test-playbook
$ tail inventory/hosts test.yml
==> inventory/hosts <==
[all]
localhost x=value_of_x y={{x}}

==> test.yml <==
---
- hosts: localhost
  tasks:
    - debug:
        var: hostvars['localhost']['y']
    - debug:
        var: y
cb 0 (.venv) [devel 704f7d7] ~/git/ansible/test-playbook
$ ansible-playbook -i inventory test.yml

PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [debug ] ****************************************************************
ok: [localhost] => {
    "hostvars['localhost']['y']": "{{x}}"
}

TASK: [debug ] ****************************************************************
ok: [localhost] => {
    "y": "value_of_x"
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

@jimi-c I don't see how this is a security issue as the variables are expanded if accessed directly (not via hostvars). Its a consistency issue, a variable should have the same value when accessed directly and via hostvars.

**Comment by tuukkamustonen** [comment]
+1

Can't comment on security, but this would be useful. I'm programmatically reading variables into build scripts doing something like:

```
ansible.inventory.Inventory(...).get_host(...).get_variables()
```

I could workaround the issue by doing manual interpolation, but that's inconvenient. Plus, doing that wouldn't probably be possible in jinja2 templates.

**Comment by iwinux** [comment]
+1

If this issue could not be fixed, the only workaround I can think of would be:

``` jinja
{{ hostvars[name].somevar|resolve }}
```

where `resolve` is a custom filter that renders the variable as a template...

**Comment by ktosiek** [comment]
@iwinux it would be more like resolveIn('somevar', hostvars[name]), and I don't know if it would be fast :-)

I think v2 changed the templating logic a bit, can anyone check there?

**Comment by jimi-c** [comment]
I just tested the following in devel (v2):

<pre>
- hosts: localhost
  gather_facts: no
  vars:
    - foo: y
      bar: "x is {{foo}}"
  tasks:
  - debug: var=bar
</pre>

with the following results:

<pre>
TASK [debug var=bar] ************************************************************
ok: [localhost] => {
    "changed": false, 
    "bar": "x is y"
}
PLAY RECAP **********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
</pre>

So I believe this issue is resolved?

**Comment by jimi-c** [comment]
I've also done a slightly more involved test, where the variable is something like `{{inventory_hostname}}` (store as `bar: "{{inventory_hostname}}"` in `group_vars/all`) which works as well, as long as the containing variable (`bar` in this case) is not resolved too early.

For example, if `bar` were in the playbook `vars` section, it would fail due to the fact that the internal variable is from inventory.

**Comment by hughsaunders** [comment]
@jimi-c Thanks! Sounds like this issue is fixed, I look forward to using v2..

**Comment by ktosiek** [comment]
@jimi-c I think you tested the wrong thing - this issue is only about accessing vars of other hosts through `hostvars` variable. I'll try to build a working test case later today.

**Comment by jimi-c** [comment]
@ktosiek ok, just let me know if you're still seeing issues on devel.

**Comment by ktosiek** [comment]
Actually, the example provided by @hughsaunders in https://github.com/ansible/ansible/issues/8213#issuecomment-64539741 still doesn't work for me:

```
$ ansible-playbook -i inventory test.yml  -c local

PLAY: ***************************************************************************

TASK [debug var=hostvars['localhost']['y']] *************************************
ok: [localhost] => {
    "hostvars['localhost']['y']": "{{x}}", 
    "changed": false
}

TASK [debug var=y] **************************************************************
ok: [localhost] => {
    "y": "value_of_x", 
    "changed": false
}

PLAY RECAP **********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

Notice the `{{x}}` in the output, it should've been `value_of_x`.
This is with pretty current devel version:

```
$ ansible-playbook --version
ansible-playbook 2.0.0 (devel 256a323de5) last updated 2015/06/24 22:14:21 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 725ce906f6) last updated 2015/06/24 22:29:47 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 44eb758dc7) last updated 2015/06/24 22:29:51 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/24 22:29:55 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/24 22:29:59 (GMT +200)
  configured module search path = None
```

The more involved example from #7844 is not working either (it uses other host's variables through hostvars to show that the right vars are used in recursive templating).

**Comment by jimi-c** [comment]
@ktosiek I believe this is not necessarily related to the original issue you reported, however I will look into it.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
