### ISSUE TITLE
file lookup fails to locate file "could not locate file in lookup"

### ISSUE THREAD

**Issue by jsmirnov** [ansible/ansible#8297]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.7/devel
##### Environment:

Ubuntu 12.04 LTS in vagrant virtual machine.
Inside vagrant box I am running ansible playbook for local machine from /vagrant folder.
##### Summary:

Ansible is not able to lookup public key to load into variable.
##### Steps To Reproduce:

Sample playbook:
_playbook.yml_

```

---
- hosts: vagrantbox
  remote_user: vagrant
  sudo: True
  roles:
     - init
```

_ansible_hosts_

```
vagrantbox ansible_connection=local
```

_ansible.cfg_

```
[defaults]
host_key_checking=false
```

_./roles/init/vars/main.yml_

```

---
ssh_users:
  - name: manager
    key: "{{ lookup('file', 'manager.pub') }}"
    shell: /bin/bash
```

_./roles/init/tasks/main.yml_

```

---
- name: ensure users exists
  user: name={{ item.name }} shell={{ item.shell }}
  with_items: ssh_users

- name: Add ssh users keys
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: ssh_users
```

_./roles/init/files/manager.pub_

```
my super secret public key here
```
##### Expected Results:

The file contents will be loaded into variable and user will be created.
##### Actual Results:

```
PLAY [vagrantbox] *************************************************************

GATHERING FACTS ***************************************************************
fatal: [vagrantbox] => could not locate file in lookup: manager.pub

TASK: [init | ensure users exists] ********************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/vagrant/playbook.retry

vagrantbox                 : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by jsmirnov** [comment]
@jimi-c 
Here is a report for `lookup` from https://github.com/ansible/ansible/issues/8233#issuecomment-50198317.

**Comment by jsmirnov** [comment]
https://github.com/ansible/ansible/blob/release1.6.9/lib/ansible/runner/lookup_plugins/file.py
https://github.com/ansible/ansible/blob/devel/lib/ansible/runner/lookup_plugins/file.py

1.6.9 and devel are quite different.

**Comment by mpdehaan** [comment]
First report I've heard on this, though we can try to reproduce this.  Thanks!

Offhand, it looks like it's trying to use the playbook dir ahead of the role path, and this line:

```
        if 'playbook_dir' in inject:
```

Should be changed to something like:

```
       if 'playbook_dir' in inject and not os.path.exists(relative_path)
```

**Comment by jsmirnov** [comment]
@mpdehaan 
I only found this issue: https://github.com/ansible/ansible/issues/7628
Not really related, but also problems with lookup plugin.

**Comment by mpdehaan** [comment]
Right, perhaps the cause, I think my comment above would fix it.

cc @jimi-c

**Comment by jimi-c** [comment]
Bisected to 2fda9bc743b66c676f07df7cc1f50bcbbdf39488

**Comment by jimi-c** [comment]
I have reverted that commit, so this issue should be resolved. Please let us know if you continue seeing any problems related to this issue. Thanks!

**Comment by jsmirnov** [comment]
@jimi-c 
confirmed. on devel branch not reproducible any more.

**Comment by jimi-c** [comment]
Great, thanks!

**Comment by hyperfocus1338** [comment]
I still have this issue on 1.9.1: https://github.com/ansible/ansible-modules-core/issues/1263

**Comment by fdutheil** [comment]
Hitting  this issue really hard with 1.9.2.
Real blocker here.

**Comment by mikesparr** [comment]
Same issue. Older versions on OSX worked. Upgraded to 1.9.x and now they all fail.

**Comment by aabognah** [comment]
Hi,

I have the same (or similar) issue and was hoping someone could help. I am trying to run a playbook that adds the public keys to authorized_keys file for a specific system user put I am getting:

fatal: [tsf-master] => Failed to template user=filetsf key= "{{ lookup('file', '/usr/local/etc/filetsf-2/.ssh/id_dsa.pub') }}" path= '/usr/local/etc/filetsf-2/.ssh' state=present: could not locate file in lookup: /usr/local/etc/filetsf-2/.ssh/id_dsa.pub

I know the file /usr/local/etc/filetsf-2/.ssh/id_dsa.pub exists!

My playbook is:

---
- hosts: all
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  
  tasks:
  - name: install ssh key
    authorized_key: user=filetsf
                    key= "{{ lookup('file', '/usr/local/etc/filetsf-2/.ssh/id_dsa.pub') }}"
                    path= '/usr/local/etc/filetsf-2/.ssh'
                    state=present"

Host: Fedora 22
Using vagrant with centos7 hosts (one management node from which this playbook fails, and three managed nodes)
Ansible 1.9.2
Vagrant v 1.7.4

**Comment by mikesparr** [comment]
@aabognah see my comment on another thread https://github.com/ansible/ansible/issues/9944#issuecomment-138628982  and this does work if you split them off to vars.  Try declaring `vars` atop your playbook and input path there, then use same syntax I did to dynamically use your var.

**Comment by aabognah** [comment]
thanks for replying @mikesparr I added the variables as you recommended but I am still getting the following error:

{"failed": true, "item": {"key": "keys/id_dsa.pub", "name": "filetsf"}, "msg": "Failed to lookup user : 'getpwnam(): name not found: '"}

I guess what confuses me is I don't understand where the authorized_key module is looking for the keys? is it looking for them on the configuration host and then copies it to the remote machine?
Do I need to copy the key files to the remote hosts? or will the authorized_key module handle that?

**Comment by mikesparr** [comment]
Your playbooks should have the files locally and the point is that the playbook installs the keys on the server, not just referencing a known location. You want to use Ansible to control what gets installed on your server so you can have exact replicas.

What you should be doing is letting the Ansible module figure out what it needs to do on the server and you simply tell it what state you want the server to be in when done. You should think of outcome and not process when using Ansible.  For example, I want the outcome of my server to have `nginx` installed. As such, I would use the `apt: service=nginx state=present enabled=yes` and let Ansible figure out what it needs to do on the server to make that happen. Don't treat it like a shell script where you explicitly need to define each step. 

In your example, you tell Ansible I want this key file X installed for user Y. It's that simple and you just tell where (locally) to find X and which user Y and it will log into the server(s) in your hosts file and perform necessary tasks. You don't need to tell it any more.

YOUR PC IS WHERE ANSIBLE SHOULD RUN AND ALL FILES SHOULD RESIDE:

```
    playbooks/
        config_my_server.yml
        roles/
            some_playbook/
                files/
                    your_key_file.pub
                tasks/
                    main.yml
                vars/
                    main.yml
```

Read more in Ansible docs and you'll learn how to organize the playbooks as such. There are some default directories and file names it will look for, but you can always just put everything in a single playbook as you have above (less reusable but fine). In your case you would have the key in a folder on your local machine you run the playbook from, then tell ansible you want that installed on the server. It's that simple.

The `authorized_key` module installs the key in the correct place so you don't explicitly tell where to place it. It appears more like you want to use the `copy` or `template` commands for what you are doing. If you truly want to install keys, you should have them in a folder structure similar to my other comment in that other ticket referenced above, and copy what I did in my task.  See the docs and if the `path` default from ansible is correct, don't worry about that param: http://docs.ansible.com/ansible/authorized_key_module.html

The trick to get the file lookup feature working is to not explicitly write in the paths with quotes (finicky) but instead reference the vars by {{ item[name] }} instead.

**Comment by mikesparr** [comment]
You do need to make sure the user exists on server before trying to install a key for them.  Before I would install keys I would do something like this:

## Create users first, then stuff with users

```
- name: Create users
  user: name={{ item['name'] }} append=yes groups='admin'
        shell=/bin/bash
  with_items: users

- name: Enable sudo without password
  template: src=sudo dest=/etc/sudoers.d/{{ item['name'] }}
            mode=0440 owner=root group=root
  with_items: users

- name: Install public keys
  authorized_key: user={{ item['name'] }} 
                  key="{{ lookup('file', item['key']) }}"
  with_items: users
```

where I had a vars file or config with:

```
---
users:
  - name: filetsf
    key: keys/filetsf.pub
  - name: jimbob
    key: keys/jimbob.pub
  - name: boblaw
    key: keys/boblaw.pub
```

and I have a template file for the sudoers update (optional but avoids password request every login)

**Comment by aabognah** [comment]
Hi,

I think I've pin-pointed the problem. It seems to be a permissions problem where the lookup operation is not able to access the file because its owned by a system user. I tried the -s, -K, -U options and non seem to work. I ended up having to run the playbook as root "sudo ansible-playbook". this worked for lookup but I have to add the root public key to the hosts or keep supplying password through --ask-pass each time.

My final playbook is something like this:

---
- hosts: all
  
  sudo: yes
  
  vars:
  - pubkey: "{{ lookup('file', '/usr/local/etc/filetsf-2/.ssh/id_dsa.pub') }}"  
  
  tasks:
  - name: install ssh key
    
    authorized_key: user=filetsf 
    
    ```
                key="{{ pubkey }}" 
    
                state=present
    ```

Regards

**Comment by mikesparr** [comment]
Glad you found it. You should, however, organize your playbooks and files together in recommended directory structure and not just reference files around you local computer. The best practice is to version control your playbooks and you wouldn't have your personal logged-in user .ssh/ folder in your repo so I'd recommend you make a copy of file for your playbooks, and get them versioned. Good luck!

**Comment by isaacegglestone** [comment]
I think you have missed the point, the problem here is that lookup isn't honouring the become=yes value.  If this is by design then it should be documented.  
Additionally in the example in the documentation:
https://docs.ansible.com/ansible/devel/modules/authorized_key_module.html

The example pulls the file from the place the author defined it as:
    key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
If you are creating users on the ansible controller then this makes sense, when you are creating users on the remote host this example doesn't make sense unless you are using the local public key on the controller to do that, (something many people do).

What your suggesting is keeping this public key with the playbook in the repo.  This may not be desirable as public keys are generated when the user is generated and keeping them in the playbook area does not make a lot of sense.

Either the example should include a way to pull the public key from the same location on the destination server or we should make lookups honour the become value.

**Comment by cod3fr3ak** [comment]
Great points Issac
