### ISSUE TITLE
Lack of v6 routing causes setup to fail

### ISSUE THREAD

**Issue by cybertoast** [ansible/ansible#882]
When doing the gathering-facts phase, playbook errors with:

```
GATHERING FACTS ********************* 
fatal: [10.0.61.18] => failed to parse:     data = run_setup(module)

  File "/home/sundar/.ansible/tmp/ansible-1345061792.18-228913620240335/setup", line 672, in run_setup

    facts = ansible_facts()

  File "/home/sundar/.ansible/tmp/ansible-1345061792.18-228913620240335/setup", line 663, in ansible_facts

    facts.update(Network().populate())

  File "/home/sundar/.ansible/tmp/ansible-1345061792.18-228913620240335/setup", line 438, in populate

    default_ipv4, default_ipv6 = self.get_default_interfaces(ip_path)

  File "/home/sundar/.ansible/tmp/ansible-1345061792.18-228913620240335/setup", line 472, in get_default_interfaces

    if words[0] == command[v][-1]:

IndexError: list index out of range

```

The problem is that on some systems (RHEL5.8 in my case) there response to `/sbin/ip -6 route get '2404:6800:400a:800::1012'` is not what's expected:

```
[~]$ /sbin/ip -6 route get '2404:6800:400a:800::1012'
RTNETLINK answers: Invalid argument
```

The solution is to ignore these errors and return an empty interfaces dictionary for this specific interface.

**Comment by mpdehaan** [comment]
want to send me a patch?

**Comment by cybertoast** [comment]
It's possible that the RTNETLINK issue is due to bad configuration someplace, but even in this case the system should not error.

**Comment by mpdehaan** [comment]
closed per #882

**Comment by alopropoz** [comment]
If IPv6 is disabled (for testing one can pass ipv6.disable=1 to kernel), ansible dies at "gathering facts" step:

```
$ ansible-playbook -c local playbook
PLAY [all] *********************

GATHERING FACTS *********************
fatal: [127.0.0.1] => failed to parse: {"verbose_override": true, "ansible_facts": {<skipped>}}
RTNETLINK answers: Operation not supported
<skipped>
$ 
```

We can not get route:

```
$ ip -6 route get 2404:6800:400a:800::1012
RTNETLINK answers: Operation not supported
$ 
```

This is handled in library/setup, get_default_interfaces(), but _low_level_exec_command() in lib/ansible/runner/__init__.py returns stdout and stderr together, so we have "RTNETLINK answers: Operation not supported" appended to JSON output which causes failure.

I fixed this in quick-and-dirty way by adding

```
if err == 'RTNETLINK answers: Operation not supported\n':
    err = ''
```

to the end of _low_level_exec_command(). It does not look like a proper way, but I'm not sure what to do here.

**Comment by mpdehaan** [comment]
Can you give me the output from "ansible --version" please?

(If still present in the latest 0.7 devel -- which should already be fixed I thought, we'd definitely want to see it fixed in library/setup, which is the module that generates these facts)

**Comment by alopropoz** [comment]
Sure. The latest.

```
$ ansible --version
ansible 0.7 (devel c04f00e3a6) last updated 2012/09/03 18:08:24 (GMT +000)
$ 
```

**Comment by mpdehaan** [comment]
cc @sfromm 
 (in case you're still interested in network facts)

reopening this.

Though please check and make sure you're not pointing to an older library path, such as if you are running from checkout but have code left over from a previous "make install" or RPM install, etc.

**Comment by alopropoz** [comment]
No installed copies, only one from checkout. Also the problem disappears when I apply mentioned fix, so it is not because of stalled version somewhere.

The first patch (August, 15) fixes gathering of interfaces info. But here is different issue: error message is still printed to stderr and _low_level_exec_command() considers it as a part of output. But later ansible tries to parse this output as JSON data and of course fails.

**Comment by mpdehaan** [comment]
I found a few places where it was not collecting stderr -- fixing that and testing now.

**Comment by mpdehaan** [comment]
Should be fixed in 8f220a4

**Comment by sfromm** [comment]
setup used to check for ipv6 support with `socket.has_ipv6`.  That should be added back so as to avoid this situation.
